# Executive Summary

Geographically, Malawi is a landlocked country in southern Africa bordering Mozambique, Tanzania, and Zambia (Masi 2017). The country has a total area of 118,484 
km2 of which 20% is covered by Lake Malawi. The country’s topography is varied. In the mountainous sections of Malawi surrounding the Rift Valley, plateaus rise 
generally 800 m to 1,200 m above sea level, although some rise as high as 3,000 m in the north. Malawi experiences sub-tropical climate conditions and annual 
changes between wet and dry seasons. The wet season generally occurs between November and April and the dry season between May and October. Average temperatures 
range between 18° and 27°C, and the wet season can bring average monthly rainfall in the order of 150 mm to 300 mm (Masi 2017). Annual rainfall ranges from 500 mm 
in low-lying areas such as the Shire Valley to above 3,000 mm in the northern highlands (USAID 2017a).

Malawi is characterized by widespread poverty, and a rapidly growing population with high population density, putting pressure on land, fisheries, water and other 
natural resources (Masi 2017). Malawi is already experiencing some of the effects of climate change with observed rising temperatures and changes in the variability 
of rainfall (Masi 2017). Adverse impacts have already resulted in considerable damage, disrupted economic activity and adversely affected the lives of large number 
of people, particularly the poor who are the most vulnerable to weather related shocks (Masi 2017). Challenges resulting from climate change include (Masi 2017): 
dry spells and seasonal droughts linked to crop failures, food security and nutrition availability; intense rainfall associated with severe riverine and flash 
floods and damaging infrastructure including roads, bridges, schools and health facilities; soil erosion due to intense rainstorms combined with ongoing degradation 
of upstream catchments causing high sediment deposition loads in rivers hence massive siltation in Lake Malawi that adversely affects hydropower energy generation; 
heat stress and outbreaks of livestock diseases like Newcastle disease in chickens and African Swine Fever in pigs; degraded grazing fields resulting to low fodder 
availability and quality; competition for resources like water and grazing land; denudation of forests and woodlands driven by biomass energy demand also causing 
biodiversity loss; increase in disease incidence and transmission of cholera, schistosomiasis and malaria.

Malawi is experiencing climate related hazards and extreme events which are increasing vulnerability of the communities to climate change across all sectors 
(Irish Aid 2018) with reports of extreme weather events (that is, droughts, heavy rains, and floods) increasing from just one during the 1970s to nineteen 
between 2000 and 2006 (Hughes et al. 2019). Mean temperatures have risen by an average rate of 0.21°C per decade, with comparative increases in 
evapotranspiration (Hughes et al. 2019). Extreme weather events that occur frequently in the country include dry spells, seasonal droughts, intense rainfall, 
riverine floods and flash floods (Masi 2017). Impacts include the Phalombe flash floods in 1991 that killed over 1,000 people, and wiped out villages, crops, 
livestock and property (REF) and an intensive 2015 flood event in XX area that left many lives and livelihoods destroyed (Irish Aid 2018). The effects of the 
climate changes and extreme weather events are compounded by a number of other factors. Extensive land use, including the massive cutting down of trees on the 
Middle and Upper Shire Valleys, has resulted in severe land degradation and soil erosion, leading to siltation of the Shire River and its tributaries, seriously 
affecting hydro-electric power generation, human health and fisheries (UNFCCC 2006). Soil degradation which is a major challenge in Malawi has soil losses 
averaged at 20 T/ha/year translating to a 4% - 25% annual yield loss (Irish Aid 2019). The average annual national soil loss rates were estimated at 29 tons per 
hectare in 2014, with soil erosion and nutrient depletion reported to affect more than 60% of Malawi’s land area. Unsustainable farming practices, an increased 
demand for agricultural land and wood fuels associated with a growing population have all been attributed to cause this degradation with chemical land 
degradation, including soil pollution and salinization/ alkalization, leading to 15% loss in the total arable land in Malawi in the last decade alone. Between 
2008 and 2016, majority of urban households relied on biomass energy with a 35% increased charcoal demand worth more than USD 66 million in 2016 providing 
employment opportunities for over 235,000 people (Hughes et al. 2019). This has a huge impact on agriculture which is the main economic activity of the country 
contributing to over 80% of the country’s GDP.

Malawi is among the dozen most vulnerable countries globally in terms of adverse effects of climate change, especially drought, but also floods/heavy rains. 
Heavy dependence on rain-fed agriculture of both the national and local economies, and for the livelihoods of the majority (85%) rural population makes Malawi 
particularly vulnerable. The rains can start as early as October, especially in the south of the country and can end as late as May, especially in the north of 
the country (Malawi, 2015). This early rains and extended rains disrupt the agricultural cycle hence having a negative impact on food production in the country. 
Factors including high population density and poverty, small landholding sizes, and the low-input low-output farming systems exacerbate farmers’ vulnerability 
and reduce the resilience of agricultural systems and adaptive capacity of farming communities to effectively respond to adverse CC impacts or take advantage of 
emerging opportunities (Zulu 2017). Malawi, with a 3.06% annual growth rate (Masi 2017), has high incidences of poverty, violence, unemployment, malnutrition, 
HIV and AIDS, high illiteracy rates, poor health, and psychological disorders which characterize the country’s young population (MDGS II 2011-2016) (Irish Aid, 
2018). About 85% of the people live in rural areas and derive their livelihoods from natural resources and agriculture (from small land holdings of between 1.0 
and 5.0 ha per household of five people), with the remaining 15% residing in urban areas (Malawi Vision 2020). The changes in climate and land cover and use are 
exacting significant adverse impacts on the economy of Malawi. A 1-in-10 year drought event would have an estimated adverse impact of 4% on the annual GDP of 
Malawi, with even larger impacts for 1-in-15 and 1-in-25 year events (Malawi 2015). The Government of Malawi (GoM) has estimated that 29 metric tons of soil per 
hectare are lost each year, costing the country an estimated 8% of its annual gross domestic product (GDP) (GOM 2001) (USAID 2017b) and for the period 2001 to 
2009, the annual costs of land degradation have been estimated at USD 244 million per year, an amount equivalent to 6.8% of Malawi’s country’s GDP. There has 
been migration from rural to urban areas (at the rate of 3.6% per year), and from densely populated to sparsely populated areas or districts over the decades 
from areas adversely affected by climatic hazards (especially floods and drought) to safer upland areas or other districts (MoECCM 20181) and in search of income 
earning opportunities (Malawi 
Vision 2020).

National Adaptation Plans (NAPs) are generally important in several ways. For instance, if countries fail to build resilience of people, places, ecosystems and 
economies to the impacts of climate change, they risk losing the hard won sustainable development gains. The most unfortunate part is that poor countries are 
more vulnerable to the devastating impacts of climate with Malawi being one of the poorest countries in the world, ranked 170 of 188 countries on the global 
United Nations Development Programme’s HDI. Given the climate related challenges faced by Malawi, a NAP will identify and provide a roadmap on key adaptation 
measures required to address key adaptation needs and processes to ensure that these measures are mainstreamed into the national planning and development 
processes and programmes across systems and sectors. The country’s Intended National Determined Contribution INDC noted the need to enhance resilience of 
productive sectors like rain fed agriculture to the associated negative impacts of climate change. The 2016 Malawi National Climate Change Policy noted the need 
to effectively manage the impacts of climate change through interventions that build and sustain the social and ecological resilience of all Malawians; with the 
regulation of greenhouse gas emissions to the atmosphere at a level that would prevent dangerous human-induced interference with the climate system within a 
timeframe that enables social, economic and environmental development to proceed in a sustainable manner. It notes that climate change needs to be integrated 
into planning, development, coordination and monitoring of key relevant sectors in a gender sensitive manner and through an appropriate institutional framework. 
The 2006 NAPA sought to increase the adaptive capacities of vulnerable communities to adverse effects of climate change through a number of initiatives, such as: 
improving community resilience to climate change by the development of sustainable rural livelihoods; restoring forest in Upper, Middle and Lower Shire Valleys 
catchments to reduce siltation and the associated water flow problems; improving agricultural production under erratic rains and changing climatic conditions; 
improving Malawi’s preparedness to cope with droughts and floods, and; improving climate monitoring to enhance Malawi’s early warning capability and decision 
making and sustainable utilization of Lake Malawi and lakeshore areas resources. The NAP process seeks to reduce vulnerability to the impacts of climate change 
by building adaptive capacity and resilience while integrating climate change adaptation into relevant new and existing national development policies, programs 
and activities.
