# Framework for the NAP

As indicated in the introduction section above, Malawi’s geographical characteristics and the prevailing socioeconomic conditions among the majority of its 
population, makes it one of the most vulnerable countries to the impacts of climate change globally. The country has been experiencing unpredictable weather 
patterns characterized by poor distribution of rainfall, causing dry spells, droughts and floods. Devastating droughts and floods witnessed in recent years and high 
temperatures cause food insecurity affecting millions of its population through low agricultural yields as a result of reduced soil moisture and inflated food 
prices. Drought lowers hydroelectric power production in the Shire River by reducing the flow rates in the river as a result of complete drying up of some of the 
tributaries that feed into Lake Malawi. Lake Chilwa, a notable wetland, is drying up. These have made agricultural production and the country’s agro-based economy 
extremely vulnerable. Land degradation and loss of soil fertility, decreasing availability of safe water for humans and livestock as water tables recede, forest 
fires, floods resulting in severe crop loss and infrastructure damage including roads and the only rail line that links the south to the centre, all result in 
serious socio-economic disruptions, food and water insecurity, and diseases such as diarrhoea, cholera and malaria. Increased temperatures, droughts, and floods 
will also result in a range of direct and indirect impacts to health, with malaria being of particular concern to Malawi because as temperatures becomes warmer, it 
will become more suitable for breeding of mosquitoes even at higher altitudes, which historically have not been exposed to the disease. All these changes among 
others are depressing economic activities, with significant impact on national GDP, and diminishing the wellbeing of the large population of rural dwellers (85%) 
whose livelihoods depend on wetlands, livestock and natural resources, as well as the urban poor who have to contend with unemployment and inequality

The National Adaptation Planning process which was initiated during the seventeenth session of the Conference of the Parties (COP) to the United Nations Framework 
Convention on Climate Change (UNFCCC) is today an essential component of planning at all levels because climate change is an issue that has to be addressed over the 
long-term. The process enables developing and least developed country (LDC) parties to assess their vulnerabilities, mainstream climate change risks, and to address 
adaptation across all key sectors that are impacted by climate change (LEG, 2012). Further, it is essential that developing country and LDC parties integrate 
adaptation planning in the broader context of sustainable development planning2 because climate change risks disproportionately magnify development challenges in 
these countries as compared to developed countries (LEG, 2012). The national adaptation plan (NAP) process was, therefore, established by the COP as a pathway by 
which effective adaptation planning in LDCs and other developing countries can be facilitated. The Government of Malawi embarked upon the National Adaptation Plan 
(NAP) process to adopt a medium-term approach for reducing vulnerability to climate change impacts, and to facilitate the integration of climate adaptation into 
ongoing planning processes at national and subnational levels.

The agreed objectives of the national adaptation plan process are (LDC-EG, 2012): (a) To reduce vulnerability to the impacts of climate change, by building adaptive 
capacity and resilience; (b) To facilitate the integration of climate change adaptation, in a coherent manner, into relevant new and existing policies, programmes 
and activities, in particular development planning processes and strategies, within all relevant sectors and at different levels, as appropriate.

The implementation of the NAP process is intended to:

- build on existing CCA planning processes and initiatives in order to provide continuity with previous planning efforts;

- build on past implementation successes;

- eliminate duplication of effort; and

- avoid repetition of implementation failures.

### Essential functions of the NAP process

The NAP for Malawi will serve the following functions:

1. Enhanced institutional coordination- Provision of oversight on climate change activity implementation by NSCCC and the NTCCC providing a platform for 
efficient and effective implementation of national, regional, and global partnerships on climate change.

2. Strengthen the capacity of Malawi’s government at all levels to implement a NAP process. MDAs will provide the data and information needed at various stages 
of the NAP process.

3. Nationally agreed adaptation targets that are mainstreamed into sectoral strategies like the MGDS III and policies which will provide for building of climate 
change resilience through regular development budgets. National Climate Change Investment Plan will assist the NAP process in resource mobilization.

4. A timetable and a work-plan to harmonize the main policy inconsistencies across Malawi’s policy and legal frameworks that are relevant to climate change 
adaptation, which again will provide for building of climate change resilience through regular development budgets.

5. Incentivized government technical officers through professional development strategies. Capacity development will entail holding regular working group 
meetings and developing training programs for working groups based on prior training needs assessment. Working group meetings will come up with terms of 
reference and a training program for climate risk and vulnerability assessments, economical appraisal and design of adaptation pathways.

6. Tools and mechanisms established to promote iterative adaptation planning. Relevant institutions, individuals and organizations involved in CCA will be 
encouraged to adopt and use this CCA blueprint to build climate change resilience and contribute to the sustainable socioeconomic development of the country.

7. Enhanced access to adaptation finance that delivers the country’s adaptation targets effectively. The National Climate Change Investment Plan and the National 
Climate Change Fund both have stipulated how they will manage fiduciary risks in dealing with the financial resources. Financial integrity in the NAP process 
will be further assured by adhering to government operating procedures on financial management and procurement as contained in Malawi’s Financial Management Act. 
In addition, the NAP budget will be tabled by the Minister of Finance to the National Assembly during presentation of the annual government budget for approval. 
All NAP work-plans will be presented to the National Technical Committee on Climate Change and the National Steering Committee on Climate Change for endorsement and approval. This will ensure accountability and transparency.


8. A promotion of private sector engagement in businesses that will meet market demand for adaptation technologies and services. This will be achieved through 
the engagement of the Malawi Confederation of Chambers of Commerce and Industry (MCCCI) as a go-between to coordinate and facilitate private sector 
engagement. There will have to be a clear plan/structure for regular and sustained engagement.

9. Identify and address capacity gaps and needs to ensure that adaptation strategies are properly designed and implemented.

### The NAP as the umbrella programme for adaptation

The National Adaptation Plan (NAP) addresses the effects of climate variability and climate change in Malawi with a systems approach – a departure from a 
sectoral approach. The framework prioritizes transformative investments for addressing the impacts of climate change on the national economy with a focus on 
building the resilience of vulnerable communities. The NAP evolves from a background of experience in the National Adaptation Plan of Action (NAPA). 
Contrastingly, the NAPA was designed to address urgent and immediate needs of the country, created to act as a channel through which the country could access 
support quickly and take advantage of win-win measures that would avoid increased damages and be more expensive to implement in the future. The NAPA was designed 
more than 10 years ago, when the country was experiencing heightened levels of vulnerability to floods, drought, and other adverse effects of climate change. 
With emerging and additional science and knowledge about climate change and its impacts, this NAP provides a framework for awareness and capacity for medium- and 
long-term adaptation in the various systems which support national socio-economic development. The current Malawi Vison 2063 (MW2063) – aspires to embrace 
ecosystem-based approaches in managing the environment. With climate change, Malawi has made commitment to develop systems to break the cycle of environmental 
degradation and increase resilience, sustainable development and planning as well as the promotion of climate change adaptation, mitigation, technology transfer 
and capacity building for sustainable livelihoods through Green Economy measures. The NAP framework is a direct contribution to the UNFCCC commitment and the 
MW2063.

There are several development programmes and activities that are taking place in Malawi at national and local governments under national government ministries 
and parastatals or through bilateral arrangements and partnerships with private sector entities, which need to be buttressed to be resilient to the impacts of 
climate changes in order to be able to effectively contribute to targeted development outcomes. Among many others, these include, for example:

- Lilongwe Water and Sanitation Project Malawi by Lilongwe Water Board jointly with Lilongwe City Council to increase access to improved water services and 
safely managed sanitation services in Lilongwe City;

- the Shire Valley Transformation Program in Chikwawa and Nsanje Districts in the south of Malawi to increase agricultural productivity and commercialization for 
targeted households and to improve the sustainable management and utilization of natural resources.

- The Social Cash Transfer (SCT), locally known as Ntukula Pakhomo Programme by the Ministry of Gender, Children, Disability and Social Welfare to cushion the 
poor and marginalized;

- The Public Works Programme (PWP) implemented by the Ministry of Local Government and Rural Development through the National Local Government Finance Committee 
(NLGFC) it provides regular payments to individuals in exchange for work, with the objective of decreasing chronic or shock-induced poverty and providing 
social protection.

- The School Feeding Program implemented by the Ministry of Education to improve child nutrition, increase children’s’ ability to concentrate in class, promote 
enrolment and regular attendance’

- The Fertilizer Input Subsidy Programme (FISP) implemented by the Ministry of Agriculture to reduce poverty and ensure the country’s food security by fostering 
an increase in agricultural productivity levels.

- The Cement and Malata Subsidy Programme that seeks to provide affordable access to building materials by the poor.

- The Increasing Access to Clean and Affordable Decentralized Energy Services (IACADES) Project under the Ministry of Energy with funding from UNDP and GEF among 
other sources.

- Community Energy, an energy company funded by the Scottish government aims to help support energy-inefficient countries and to implement new energy-based 
programs to provide electricity to rural areas, focusing on personal electricity and solar projects, as well as hydro and cooking stoves for communities in 
rural areas, with 104 rural communities benefitting so far from the installation of install personal renewable energy units. Twelve districts of Malawi have so 
far received direction and access to these units, and each will begin to produce and regulate their own energy, with Community Energy’s support.

Given its cross-cutting nature which includes, inter alia, considerations of adaptive capacity and resilience at systems level while considering also the 
individual, institutional, and systemic factors, and its mainstreaming into governance and development planning structures, the NAP offers an appropriate 
umbrella under which national programmes for adaptation can be jointly framed, coordinated and implemented. The NAP will present an aggregate national adaptation 
plan that will link to appropriate local, subnational, national, and sectoral activities and action plans, maximise on efficiencies, minimise duplication of 
efforts, and leverage on cost constraints to programme implementation. The NAP process shall also add value to past and current activities by identifying 
capacity gaps, especially for the design and implementation of medium-term climate change adaptation priorities, as well as by accessing opportunities for 
international funding to develop more effective climate responsive planning and budgeting. The Malawi NAP coalesces all the discrete climate change adaptation 
plans and programmes that are or shall be implemented in the country. It comprises of collated, synthesised and analysed data of climate change trends and its 
impacts, aggregated from local level and downscaled from regional analyses, as well as related peculiar vulnerabilities at scale within and across regions and 
systems, and identifies gaps and capacity needs that should be addressed. This information will be used to identify and prioritise adaptation options, and to put 
in place plans to implement the proposed adaptation options, as well as how to finance them. Finally, a monitoring and evaluation framework is determined for the 
different programmes to track progress and to make adjustments where necessary. Periodic updates (every four years) shall be undertaken to ensure that the NAP is 
responsive to new and emerging needs and offers an effective mechanism for climate change adaptation at scale.

### Coherence with national development context, SDGs, Sendai and other relevant frameworks

The Malawi Vision 2020 is anchored on six pillars, namely; Good governance and a capable state, Human resource development and a knowledge-based economy, Private 
sector-led development, Infrastructure development, Productive high value and market-oriented agriculture, and Regional and international integration. The vision 
noted that air pollution and climate change issues though then relatively small could become serious challenges if unchecked. The vision hence identified the 
strategic challenges to prevent air pollution and climate change issues as: monitoring emissions of hydrocarbons nitrogen oxides and carbon monoxides; proper 
management of hazardous substances and wastes; use of ozone friendly technology; establishing regulations and enacting legislation on air pollution; and 
promoting education on climate change issues. The Malawi vision statement highlights Malawi as an ‘environmentally sustainable,’ ‘self-reliant with equal 
opportunities for and active participation by all,’ and ‘having social services, vibrant cultural and religious values and being a technologically driven middle-
income country.’ This aligns with the vision of the NAP vision for Malawi of “a country with people, ecosystems and infrastructure that are resilient and have 
adaptive capacity to the impacts of climate change.”

The government of Malawi developed the National Climate Change Management Policy 2017-2027, to assist the country achieve its long term goal for climate change 
management, which is to reduce the socio-economic impacts of adverse effects of climatic change. The NCCM policy is in line with other national strategies and 
plans. For example, the Malawi Growth Development Strategy II 2011-2016 recognizes that climate change, environment and natural resources management as key 
priority areas that needs to be responded to using appropriate approaches because it contributes to lower land quality, heightens extreme weather conditions 
(e.g. recurrent droughts, heavy rain falls and floods) which sometimes lead to emergency relief efforts that divert much needed finances from development 
projects, and has significant adverse consequences for agriculture, food security, poverty and vulnerability. The process of developing the MGDS III 2017-2022 
considered all the international commitments that Malawi made which include the SDGs, African Union Agenda 2063, SADC RISDP, and other regional treaties. The 
government advocated for alignment of the SDG to all sector and institutional programming. This guaranteed that all development intervention from the cooperating 
partners are well aligned towards the SDG timely tracking and reporting of all the agreed indicators. On the other hand, Malawi is also committed to implement 
the Sendai Framework for Disaster Risk Reduction 2015-2030 as it strives to achieve various SDGs since Malawi is suffering the impacts of disasters both from 
climate change as well another natural causes. The commitment goes beyond the 2030 agenda as it is clear that resilience building is paramount importance if the 
development gains being achieved in all the national efforts should be sustained. Malawi is therefore well placed to enact and mainstream a NAP to operationalize 
its approach to adaptation to climate change and to monitor progress towards desired outcomes.
