# Approach and Methodologies

## Guiding principles
In line with the principles established by the UNFCCC and also in line with Malawi's development goals, the guiding principles for the NAP process are as follows: 
developing sustainably; uplifting the poor and the vulnerable; respecting the critical role of gender; encouraging participation and ownership; incorporating 
traditional and Indigenous knowledge, and proceeding with financial accountability and integrity.

a. A country-driven approach. 
country-driven approaches inspire ownership and ensure that plans, programmes and activities are aligned with national priorities.

b. Sustainable development 
Sustainable development is defined as "development that meets the needs of the present without compromising the ability of future generations to meet their own 
needs" (United Nations, 1987).

c. Uplifting the poor and the vulnerable 
Poor people in Malawi, who are also the majority, are the most affected by climate change impacts and have the least means of adapting to these impacts. Rural, 
urban and peri-urban poor people bear the brunt of climate-related disasters such as floods because their communities suffer from weak infrastructure. When drought 
and famine occur, the poor can also cope because of low incomes and reliance on rain-fed agriculture. Malawi's NAP will, therefore, among other principles, be 
guided by pro-poor principles to ensure inclusiveness. The NAP will ensure that the poor and vulnerable, including women and children, are targeted and benefit from 
the planning and implementing climate change adaptation interventions. The main objective of this principle is poverty reduction. This principle is in line with 
Malawi's Vision 20/20 and SDG 1.

d. Gender and social inclusion, and particular consideration of marginalized groups such as women
The NAP will ensure that Malawi's Gender Policy (2015) principles—gender parity, women's empowerment and upholding women's rights—guide the process. The process will include the youth who are already engaged through various climate change youth networks

e. Participation NAP Process and ownership
This is a critical guiding principle for the NAP. It will allow full involvement of stakeholders and beneficiaries in the NAP activities, thereby enabling 
information sharing and minimizing efforts' duplication. Soliciting the views of stakeholders at each step of the NAP will ensure their ownership, which will 
positively affect the outcomes. There are many actors in the climate change adaptation field that are already carrying out various activities. These will now be 
engaged with the NAP process guided by the framework, which will result in increased focus in terms of planning and funding for adaptation activities. This is 
important because adaptation activities have long been underfunded at both the central and district level. Stakeholder participation is necessary for buy-in, 
ownership, involvement in, and support of planned activities.

f. Incorporating traditional and indigenous
While scientific methods of weather forecasting have evolved in the last 100 years or so, rural communities the world over have traditionally relied on 
Indigenous forecasting methods. In Malawi, communities have used local Indigenous methods to predict good or bad years by using cloud observations (appearance), 
wind directions, stars, and the behaviour of animals, insects and plants. Indigenous local knowledge of weather forecasting is useful in decision making at the 
village level. The NAP process will encourage integrating Indigenous knowledge with the scientific knowledge of weather forecasting. The process requires that 
communities be engaged to identify knowledge integrated with science, which could then be further disseminated for use by scientists, practitioners and policy-
makers.

g. Financial accountability and integrity
Resources allocated to climate change adaptation programs can greatly increase over time if there is confidence that these resources will be spent prudently, be 
quickly accessed, and produce the intended results. This calls for good fiduciary governance of the resources. The National Climate Change Investment Plan and 
the National Climate Change Fund have stipulated how they will manage fiduciary risks in dealing with the financial resources. Financial integrity in the NAP 
process will be further assured by adhering to government operating procedures on financial management and procurement as contained in Malawi's Financial 
Management Act. Besides, the NAP budget will be tabled by the Minister of Finance to the National Assembly during the annual government budget presentation for 
approval. All NAP workplans will be presented to the National Technical Committee on Climate Change and the National Steering Committee on Climate Change for 
endorsement and approval. This will ensure accountability and transparency.

g. A multidisciplinary and complementary NAP approach, building upon relevant existing plans and programmes 
Multidisciplinary and complementary approaches are essential in the NAP approach because adaptation is itself multidisciplinary and cross-cutting. The country 
has mainstreamed climate change issues in its development plans because it has implications for employment creation and economic growth. Its impact on various 
economic sectors such as agriculture, health and nutrition, tourism, and natural resources has been well established.

l. Simplicity and flexibility of procedures based on the country's circumstances
Simplicity is important where actions are planned in multidisciplinary and multi-institutional/multi-agency contexts coupled with strong involvement of the 
public and private sector, communities and individuals. Flexibility is important, as adjustments can be made to improve different aspects of implemented 
programmes.

m. Alignment with the GCF country programme.
This alignment is important to improve access to funds such as the Green Climate Fund. Such alignment would include coherency with the national climate change 
policy and related strategies and plans, coherence with existing policies, the executing entity's capacity to deliver, and stakeholder consultations and 
engagement.

### Guidelines used
The main guidelines used included:

· The Technical Guidelines for the National Adaptation Plan Process, UNFCCC – this was used as the primary document for framing of the structure and content of the NAP. It also requires that the NAP process: follows a country-driven, fully transparent, approach; is based on and guided by the best available science and, as appropriate, traditional and indigenous knowledge; and facilitates country-owned, country-driven action and not be prescriptive, nor result in the duplication of efforts undertaken in-country.

- Malawi National Climate Change Policy-2017-2027

- Malawi Second National Communication-2011

- Malawi Vision 2020

- The Malawi Growth Development Strategy 2017-2022

- Malawi Intended Nationally Determined Contribution

- National Adaptation Plan of Actions-2006

- Malawi NAP Stocktaking Report 2016

- National Climate Change Investment Plan (2013-2018)

- National Environment and Climate Change Management 2012-2016

- National Strategy for Sustainable Development

- Malawi Strategy on Climate Change Learning

In addition, and following the experiences gathered from the implementation of the NAPA process, the Technical Guidelines recommend:

- using locally defined criteria for ranking vulnerabilities and prioritizing project activities, which will build confidence and buy-in across all stakeholders;

- using available data and assessments as a basis for more comprehensive assessments; and

- engaging national experts, as this will also enhance the experience and capacity of the country.

These were supported with emerging new data from the published literature. The assessment of these documents together included:

a. Process of identification/stocktaking of desirable and available information
- i. Climate and socio-economic data and information</li> 
- ii. Current assessments: Exploring possibilities for further assessments
- iii. Policies, strategies, plans
- iv. Existing initiatives on adaptation

b. Resource mobilization for the process.

### A systems approach to adaptation
Systems are complex, and each system interacts to various degrees with other related systems. Sectoral interventions have not been as successful as desired 
because they do not take into account the interactions of system components, including the fact that the mandate to manage some components of the system may lie 
in a different sector, and hence come under a different institutional mandate whose primary goal is not necessarily in tandem with those of another sector, and 
more often than not, there is very little synergy between sectoral programmes.

Urban areas, for example, are complex since many social, physical and economic systems meet and interact, with many of these extending well beyond its spatial 
boundaries, e.g. water and power supply systems, while other linkages may be transboundary. It is important, therefore, that National Adaptation Plans capture 
these systems and their interlinkages, scale and stakeholder diversity, so that appropriate and synergistic adaptation measures can be devised and implemented. 
Thus, the NAP process uses a systems approach which facilitates the integration of climate change adaptation, in a coherent manner, into relevant new and 
existing policies, programmes and activities, in particular development planning processes and strategies, within all relevant sectors and at different levels, 
as appropriate.

The framework to guide the assessment of vulnerabilities and risks included:
- i. Conceptual framework of vulnerability and risk at various levels: national, system level, local level, etc.
- ii. Boundary conditions for the assessment using the period 1971-2000 for baseline climate but also extended further back into time where data is 
    available.
- iii. Focus on key systems/sectors
- iv. Synergy with SDGs, Sendai Framework for DRR, and other relevant regional and national frameworks.

### Other unique considerations
The emergence of the COVID-19 pandemic in early 2020 disrupted globally, established societal structures and ways of doing things, and has had devastating 
impacts on human health, stressed health systems and severely disrupted national economies. A UNDP 2020 study “Covid-19 Pandemic in Malawi Final Report June 
2020” shows the high levels of vulnerabilities of individuals, households and the whole Malawian economy affecting negatively on almost all sectors of the 
economic growth in the country. The study projects that the negative impacts of COVID-19 on the economy are projected to persist for more than 10 years. The open 
NAP initiative in Malawi has been developed with Malawi being one of the 11 Africa-Asia-Pacific region beneficiaries of GCF funding of a mitigation-themed 
project named Climate Investor One. However, more funding of projects from other funding sources like LDCF, SCCF, GEF and Adaptation Fund among other sources has 
not been materialized perhaps due to lockdowns and poor internet access across the country affecting personnel availability to apply for funding as well as 
undertake the projects. It is however hoped that the situation will normalize and that COVID-19 will be properly managed so as more funding will be availed to 
Malawi to continue developing this NAP and more funds can be used to develop the next NAP.

### Road Map
This particular process was initiated in 2016 with a stakeholder engagement workshop (Figure XX). Milestones in the process are illustrated in Table XX below, 
with the goal of mainstreaming the NAP into the Malawi Growth and Development Strategy (MDGS III).

insert diag here
