---
output:
  pdf_document: default
  html_document: default
---
# National Context

## National circumstances
**Environment:** Malawi’s landscape has a varied topography and is dominated by the Great Rift Valley, which runs north to south and contains Lake Malawi and the Shire River Valley. To the west are the central plateaus, highlands (Nyika and Viphya in the north and Shire in the south) and isolated mountains (Mulanje and Zomba) (USAID, 2017a). In the mountainous sections of Malawi surrounding the Rift Valley, plateaus rise generally 800m to 1,200m above sea level, with some especially in the north rising as high as 3,000m. To the south of Lake Malawi lie the Shire Highlands, approximately 900m above sea level. The Shire River plays a very significant role in Malawi by providing water for generating hydropower (98% of Malawi’s electricity), agriculture, fisheries, transport, tourism, urban and rural water supply along its length, impacting the livelihoods of over 5.5 million people in the southern region of Malawi (Masi, 2017). Freshwater for irrigation in Malawi’s plantations such as Illovo Sugar at Nchalo is obtained from the Shire River; as well as other domestic and industrial uses (UNFCC, 2006). Malawi has multiple important waterbodies including Lake Malawi, (the third largest African Rift Valley Lake), Lakes Malombe, Lake Chilwa, and Lake Chiuta(USAID, 2015). Other rivers in Malawi providing water comprise of North and South Rukuru and Songwe in the Northern Region, Linthipe, Bua and Dwangwa in the Central Region, and Shire and Ruo in the Southern Region (Global Water Partnership, 2016).

In 2005, forest area coverage was at 24.3% while cultivated land covered 33.7%, shrubs and savanna woodlands covered 19.9% and the remaining 22.1% of Malawi was 
covered by water. In the upper Shire River catchment, there was an 18 % increase in agricultural land in the 1989 to 2002 period (Mtilatila et al. 2020). Forests 
and trees impacts livelihoods and the economy through the supply of biomass fuels, provision of habitats for wildlife and biodiversity, prevention of land 
degradation, protection of watersheds and acts as sources of soil fertility (Hughes et al. 2019). Malawi has the highest deforestation rate in sub-Saharan Africa 
with the government of Malawi estimating that the annual rate of deforestation in Malawi is 1.0–2.8%. Estimation shows that the ratio of forest area decreased from 51% to 33% from 1990 to 2010 (Mapulanga and Naito, 2019). Malawi has very low greenhouse gas (GHG) emissions of around 1.4 tons CO2 equivalents (CO2e) per capita in 2015 by global standards (Hughes et al. 2019). According to Malawi’s Nationally Determined Contribution (NDC), the main sectors contributing to GHG emissions are as at 2015, forestry at 78% of the emissions, agriculture at 16% and energy at 4% (Irish Aid, 2018).

Soil degradation is a major challenge with soil losses averaged at 20 T/ha/year. This translate in a yield loss of 4% - 25% annually (Irish Aid 2019). In 2014, the average annual national soil loss rates were estimated at 29 tons per hectare, and soil erosion and nutrient depletion are reported to affect more than 60% of Malawi’s land area. The main causes of this degradation are unsustainable farming practices, increasing demand for agricultural land and wood fuels associated with a growing population. Chemical land degradation, including soil pollution and salinization/ alkalization, has led to 15% loss in the arable land in Malawi in the last decade alone. The annual costs of land degradation between 2001 and 2009 have been estimated at USD 244 million per year-an amount equivalent to 6.8% of Malawi’s country’s GDP. Between 2008 and 2016, urban household demand for charcoal increased by 35% and was worth more than USD 66 million in 2016 and provided employment opportunities for over 235,000 people (Hughes et al. 2019).

**Climate:** The majority of the country experiences a cool tropical continental climate, characterized by two distinct seasons: a rainy season from November to 
April and a dry season from May to October. Annual rainfall ranges from 500 mm in low-lying areas such as the Shire Valley to above 3,000 mm in the northern 
highlands. Overall rainfall exhibits high inter-annual variability and is highly influenced by the El Niño Southern Oscillation (USAID, 2017a). The rains can 
start as early as October, especially in the south of the country and can end as late as May, especially in the north of the country (Malawi, 2015). The warm-wet 
season stretches from November to April, during which 95% of the annual precipitation takes place. Malawi experiences large heterogeneity in rainfall regime, and 
there are big differences between the North, Central and South regions. Annual average rainfall varies from 725mm to 2,500mm with Lilongwe having an average of 
900mm, Blantyre 1,127mm, Mzuzu 1,289mm and Zomba 1,433mm (Masi, 2017). In the south of Malawi, the wet season normally lasts from November to February bringing 
around 150‐300m per month, but rain continues into March and April in the north of the country as the ITCZ migrates northwards. Inter‐annual variability in the 
wet‐season rainfall in Malawi is also strongly influenced by Indian Ocean Sea Surface Temperatures, which can vary from one year to another due to variations in 
patterns of atmospheric and oceanic circulation. The most well documented cause of this variability is the El Nino Southern Oscillation (ENSO) (UNDP, n.d.).

Average daily temperatures vary with seasons and elevation, with the coldest temperatures (12–15°C) in July in the highlands and the hottest (25–26°C) in October 
in the Lower Shire Valley (USAID 2017a). Mean annual temperature has increased by 0.9°C between 1960 and 2006, an average rate of 0.21°C per decade (Irish Aid 
2018). A cool, dry winter season runs from May to August with mean daytime temperatures varying between 17 and 27°C, and temperatures falling between 4 and 10°C 
at night. A hot, dry season lasts from September to October with daytime temperatures between 25 and 37°C. The wet season generally occurs between November 
and April and the dry season between May and October. Average temperatures range between 18° and 27°C, and the wet season can bring average monthly rainfall in 
the order of 150mm to 300mm (Masi, 2017; UNDP, n.d.). Between 1967 and 2003, the country experienced six major droughts and incidences of flooding. 2011-12 
droughts had severe effects on food security in many districts in Malawi, with approximately 2 million people affected, particularly in the southern districts. 
(Irish Aid, 2018). Floods in Malawi have been associated with heavy upstream rainfall resulting in too much water downstream that leads to the breaking-up of 
river banks. This is a common feature on the North Rukuru in Karonga, Likangala in Zomba, and the Ruo/Shire Rivers in Chikwawa/NsanjeMalawi has also experienced 
flush floods due to prolonged torrential rains, such as the Phalombe flush floods in 1991 that killed over 1,000 people, and wiped out villages, crops, livestock 
and property (UNFCC, 2006). Intensive flooding in 2015 left many lives and livelihoods destroyed (Irish Aid, 2018).

**Political context:** The Republic of Malawi is a sovereign State with rights and obligations under the Law of Nations (Malawi Constitution, Chapter one). There 
shall be a President of the Republic who shall be Head of State and Government and the Commander-in-Chief of the Defense Forces of Malawi (Article 78). The 
President shall be elected by a majority of the electorate through direct, universal and equal suffrage (Article 80(2)). The National Assembly of Malawi is the 
supreme legislative body of the nation. The National Assembly has 193 Members of Parliament (MPs) who are directly elected in single-member constituencies using 
the simple majority system and serve five-year terms. Malawi is a member of the United Nations, the Commonwealth of Nations, the Southern African Development 
Community (SADC) (Malawi 2017), the Common Market for Eastern and Southern Africa (COMESA), and the African Union (AU). Malawi was a one party state since 
attaining her independence until 1993 when it became a multi-party state (Masi, 2017).

**Legislative context:** The GoM prioritizes climate change, natural resources, and environmental management in its development strategy, the Malawi Growth and 
Development Strategy (MGDS II 2012–2016). The GoM has also invested in the Green Belt Initiative (GBI); an initiative which seeks to transform Malawi, through 
irrigation, from a predominantly consuming and importing country to a producing and exporting country (USAID, 2013). In 2016, Malawi made an ambitious 4.5 
million hectares restoration pledge to the Bonn Challenge and the African Forest Landscape Restoration Initiative (AFR100) by 2030 estimated at a cost of 
approximately 279 billion MWK or approximately 62000 MWK per hectare (USAID,2017b). GoM in partnership with the World Bank and African Development Bank has 
formulated this Strategic Program for Climate Resilience (SPCR) under the Pilot Programme for Climate Resilience (PPCR) to act as a framework for addressing the 
challenges of climate change that impact on the national economy and community livelihoods. The SPCR will build on the available enabling frameworks and efforts 
in climate resilience-building programs as stipulated in the Malawi Growth and Development Strategy III, National Climate Change Management Policy (2016), 
National Agriculture Policy (2016), National Climate Change Investment Plan (2013), and Malawi’s Nationally Determined Contribution under the UNFCCC (2015).

Malawi is a signatory to various international treaties, instruments and that cover climate change. These include the United Nations Framework Convention on 
Climate Change (UNFCCC) and the Kyoto Protocol. These treaties and instruments oblige the country to take various actions to address climate challenges including 
putting in place instruments such as climate change policies and legislation. Malawi is a member of the Least Developed Countries’ (LDCs) Group, the LDC Expert 
Group (LEG), and currently has a seat on the board of the Adaptation Committee and the Green Climate Fund (GCF) Board (Masi, 2017). The Government has put in 
place a series of legislative sectoral frameworks and strategies to integrate environment and climate change management in socio-economic development activities. 
Key ones include: Vision 2020; the Malawi Growth and Development Strategies; National Environmental Policy (NEP) 2004; NAPA 2007; National Climate Change 
Investment Plan (2013); Malawi Energy Policy (2003); Food Security Policy (2006); Disaster Preparedness and Relief Act (DPRA) (1991); Environment Management Act 
(1996) and the Disaster Risk Management Policy 2015 (Irish Aid, 2018).

**Social context:** According to the World Population review, January 2018, Malawi has a land area of 118,484 square kilometers, with an estimated population of 
18,921,352 million which ranks 61st in the world. Malawi still has a fairly low population density of 129 people per square kilometer (86th in the world). 
However, Malawi is growing rapidly with a 3.06% (Masi, 2017) annual growth rate. High incidences of poverty, violence, unemployment, malnutrition, HIV and AIDS, 
high illiteracy rates, abuse, poor health, and psychological disorders characterize the country’s young population (MDGS II 2011-2016) (Irish Aid, 2018). About 
85% of the people live in rural areas and derive their livelihoods from natural resources and agriculture (from small land holdings of between 1.0 and 5.0 ha per 
household of five people), with the remaining 15% residing in urban areas. About 48% of the population is below 15 years of age. The overall average life 
expectancy as of 2008 statistics was 37 years with fertility rates declining from 7.6 in 1984 to 2.8% in 2008 and later rising to 6.7 (Malawi Vision 2020). There 
has been migration from rural to urban areas (at the rate of 3.6% per year), and from densely populated to sparsely populated areas or districts over the decades 
from areas adversely affected by climatic hazards (especially floods and drought) to safer upland areas or other districts (Ministry of Environment and Climate 
Change Management Environmental Affairs Department, 2018) and in search of income earning opportunities (Malawi Vision 2020). 33150 cases and 981 deaths were 
recorded in Malawi’s worst Cholera outbreak. Waterborne infectious diseases are a leading cause of child mortality and contribute to forms of growth retardation, 
including stunting and wasting with 48 to 53 percent of children under the age of five suffering from stunted growth (Republic of Malawi, 2012). Overall, records 
as to disaster damage provided by Department of Disaster Management Affairs, DoDMA and the Prevention Web (by The United Nations Office for Disaster Risk 
Reduction, UNISDR) give critical information related to human and economic losses resulting from the disasters that have occurred in Malawi within last three 
decades. More than 47 natural disasters were recorded in the last three decades and these disasters range from droughts, earthquakes, epidemics, floods and 
storms. In these natural disasters, a total of 2,775 people were killed with an average of 90 people killed per year. Most of these (60%) died due to epidemics 
(National Water Resources Masterplan- Part II masterplan). Malaria is the most common disease in the lake areas, followed by respiratory infections, diarrhea, 
anemia, and bilharzia/schistosomiasis. HIV/AIDS and other sexually transmitted infections (STIs) are also common. Research conducted by Madsen et al. between 
1998 and 2007 found a high prevalence of schistosomiasis in communities living along the shores of Lake Malawi. They found that the prevalence of urinary 
schistosomiasis ranged from 10.2% to 26.4% in inland villages and from 21.0% to 72.7% in lakeshore villages. Infection rates were higher among school age 
children ranging from 15.3% to 57.1% in inland schools and from 56.2% to 94.0% in lakeshore schools. The HIV infection rate in Malawi as a whole was 10.3% in 
2010 (UNAIDS) (USAID, 2015).

**Economic context:** Agriculture is central to Malawi’s economy, contributing nearly 40 percent of GDP and roughly 90 percent of the country’s export earnings 
(USAID, 2017a). Maize is a dominant crop in Malawi, accounting for 28.8 percent of agricultural GDP. Groundnut is an important smallholder food and cash crop in 
Malawi contributing 1.6 percent to agricultural GDP. Soya and sunflower account for 13 percent of that sector’s total intermediate input expenditure, and account 
for 1.9 percent of agricultural GDP (Aragie et al. 2018). The agriculture sector is the driver of Malawi’s economy and provides employment to 85% of the 
workforce, and contributes 85 to 90% of foreign exchange earnings and 60 to 70% of raw materials for the manufacturing sector (UNFCCC, 2006). Over half (51%) of 
Malawi's predominantly rural (86%) population live below the national poverty line, most (85%) dependent on agriculture for livelihood, and on only $320 United 
States Dollars (USD) per capita per year (Chinsinga, Chasukwa and Naess 2012; World Bank 2014; Zulu 2017). Average annual headline inflation in 2016 stood at 
22.6%, slightly lower than the 2015 figure of 21.0%, with rising food inflation as the main driver. Power generation reduced by 30% due to low levels in the 
Shire River affecting economic activities in sectors such as manufacturing, which experienced low capacity utilization. Malawi’s overall GDP grew at only 2.7% in 
2016, down from 2.9% in 2015. According to the poverty statistics for 2010, 70.9% of the people in Malawi are living on less than $1.90 a day. The people living 
below the national poverty line are 50.7% and the country inequality trend (GINI Index) stands at 46.1 (Irish Aid 2018). According to the United Nations 
Development Program’s Human Development Report for 2014, about 62% of the population in Malawi lives on less than US $1.25 a day and 89% lives below the US $2 a 
day threshold (USAID, 2015). Tobacco is Malawi’s largest export cash crop, accounting for over half of export earnings, followed by tea and sugar (Purchase from 
Africans for Africa. n.d.; FAO, n.d.; and World Bank, 2012). Fishing contributes about 4% to Malawi’s Domestic Product (GDP) and accounts for 60–70 percent of 
Malawians’ animal protein intake. An estimated 1.6 million Malawians derive at least some income from fishing, fish processing, marketing and trading, boat and 
gear-making, and allied industries (Brummet and Noble, 1995; Andrew et al. 2003). Wildlife is a valuable tourism resource as it can contribute significantly to 
incomes and employment. The sector, however, faces a number of challenges including poaching, poor supporting infrastructure, and low community participation in 
wildlife conservation (USAID, 2013).

Malawi is one of the poorest countries in the world, ranked 170 of 188 countries on the global United Nations Development Programme’s HDI. More than 70% of the 
population lives below the international poverty line of USD 1.90 per capita per day and GDP per capita is just USD 372 (2015). Both inequality and poverty rates 
are high. About 20.7% of the people are so poor that they cannot afford to eat a minimum daily recommended food intake, and at least 37% of children under five 
are chronically undernourished and stunted (low weight for age). Malawi’s wealth per capita, USD 8,409 in 2014, is much lower than the average for other low-
income countries (USD 13,629) or for Sub-Saharan Africa as a whole (USD 25,562) (Hughes et al. 2019). Real gross domestic product (GDP) grew by 5.7% in 2014, but 
slowed down to 2.5% in 2016 after floods in early 2015 followed by two consecutive years of drought, which has adversely affected the performance of agriculture, 
which accounts for about a third of the country’s GDP. The country has a GDP of US$ 6.4 billion (2015 data), and per capita income (2015 data) is US$ 34011. 
Malawi is a low-income country with 74% of Malawians earning US$ 1.25 per day or less. Using national poverty headcount, approximately 50.7% of the population 
live below the national poverty line. About 24.5% are considered ultra-poor, meaning that they cannot afford to meet the minimum standard of the daily 
recommended food requirement. Levels of chronic malnutrition are very high at 42%, wasting is at 4% and underweight prevalence is at 13%. The 2015 flood damage 
cost event estimated at US$ 335 million, equivalent to approximately 5% of GDP. Land degradation is estimated to cost the equivalent of 5.3% of GDP each year 
with soil degradation a significant factor that contributes between 4 and 25% to the loss of agricultural yields in Malawi (Masi, 2017).

Lake Malawi provides the main source of the country’s fish production. Other important sources include Lake Chilwa, Lake Malombe and the Elephant Marsh. The 
sector has experienced considerable decline of commercially important fish species like Chambo (Oreochromis spp.) from around 30,000 Mt a year in the late 20th 
century to about 2,000 Mt annually in recent years from Lake Malawi caused by overfishing and climatic influences which result in reduced water levels and 
disrupt fish breeding and nursery sites. Weak governance capacity to enforce fisheries regulations, and control of illegal fishing and destruction of habitats, 
contribute to reduced abundance of fish stocks and fisheries resources in Malawi (Masi, 2017).  The National Human Development Report of 2001 ranks Malawi as one 
of the lowest in terms of Human Development Index (HDI), placing it at number 163 out of 173 countries in the world (United Nations Development Programme 
(UNDP)/Malawi Government (MG), 2001). It is one of the poorest countries in Africa, with about 65% of its population living below the poverty line in 1998, and 
29% living in extreme poverty (MG, 1995, 2000; MoA, 2005; UNFCCC 2006). The manufacturing sector currently makes a small contribution to national income (12% of 
GDP) and employment and there is limited industrial diversification. In addition, there are weak inter and intra-industry linkages (Malawi Vision 2020). 

**Technological context:** It is the aspirations of Malawians through their Malawi’s Vision 2020 to have a science and technology-driven economy. A developing 
country such as Malawi needs information technology to achieve development in all spheres of human endeavor. However, promoting the use of IT is the main 
challenge (Malawi Vision 2020). Greater use of geospatial technologies such as aerial surveys, satellite monitoring, and drone surveys could help address the 
limited human resources at field levels. Mobile phone technologies are rapidly improving communication and services with growing opportunities for informing 
Malawians on environmental issues (Hughes et al. 2019). The media plays a key role in raising public awareness on climate change issues especially in informing 
rural communities who suffer most due to adverse impacts of climate change due to their low adaptive capacity (Ministry of Environment and Climate Change 
Management Environmental Affairs Department, 2013-2018). The systematic use of new cell phone technologies, social media, video documentaries, radio and TV 
programs, and other information-communication technologies can greatly accelerate the widespread knowledge of proven restoration interventions (Ministry of 
Natural Resources, Energy and Mining, n.d.). 

### Legal frameworks 
The vision of Malawi’s NAP aligns with the Malawi Growth and Development Strategy III (2017-2022). MGDS III is anchored in Water Development, Agriculture and 
Climate Change. The NAP process will address climate change management through improved community resilience to climate change through enhanced agricultural 
production, infrastructure development and disaster risk management.  The MGDS III adaptation strategies for Agriculture, Water Development and Climate Change 
Management include increased agricultural production and productivity, increased land under irrigation; increased agricultural diversification, enhanced 
agricultural risk management, enhanced integrated water resources management at all levels, and improved weather and climate monitoring for early warning, 
preparedness and timely response. These will be the strategies the NAP will also prioritize. The MGDS III goals are premised on Malawi's long term development 
aspirations well laid out in Vision 2020.Malawi has also prioritized climate change, environment and natural resources management among the priorities within 
priorities of the Malawi Growth and Development Strategy (MGDS II). Government of Malawi has also developed the National Climate Change Management Policy (NCCMP) 
whose goal is to promote climate change adaptation, mitigation, technology transfer and capacity building for sustainable livelihoods through Green Economy 
measures for Malawi. The policy outlines six priority areas for climate change management in the country which include: Climate change adaptation, Climate change 
mitigation, Capacity building, education, training and awareness, Research, technology development and transfer, and systematic observation, Climate change 
financing, Cross-cutting issues like gender consideration, population dynamics and HIV and AIDS.  

The NCCMP policy statements are:  

1. Reduce vulnerabilities of populations in Malawi and promote community and ecosystem resilience to the impacts of climate change; 

2. Ensure that women, girls and other vulnerable groups are engaged and involved in planning and implementing climate change adaptation interventions; and 

3. Ensure that communities are able to adapt to climate change by promoting climate change adaptive development in the long term. 

4. Promote the reduction of greenhouse gas emissions; and 

5. Enhance carbon sinks through re-afforestation and sustainable utilization of forest resources. 

6. Build capacity in all sectors and at all levels in climate change to attain socio-economic development utilizing the principles of green economy; and 

7. Address capacity gaps on investment in skills and capabilities for negotiations, mechanisms for reducing emissions while supporting prudent environmental 
management and sustainable economic growth.  

8. Enhance research, technology and systematic observation for climate change management, supported by appropriate capacity development and dedicated financing 

9. Encourage resource mobilization and commitment of government for the prioritized technologies. 

10. Enhanced financing for implementation and coordination of climate change management activities through increased national budgetary allocation, establishment 
of a Climate Change Management Fund, improved access to international climate financing (both multilateral and bilateral) and private sector investments. 

11. Mainstream gender and issues affecting the disadvantaged groups into all climate change strategies, plans and programmes. 

12. Integrate population issues into climate change management in the development agenda through an integrated approach which would reduce poverty, protect 
natural resources and reduce inequality. 

13. Incorporate HIV and AIDS as well as gender considerations in all climate change interventions including adaptation, mitigation, capacity building and 
technology development and transfer. 

The Government of Malawi through their Vision 2020 and the Malawi Constitution 1995 has put in place a series of legislative sectoral frameworks and strategies 
to integrate environment and climate change management in socio-economic development activities. These include:  

- i. The Malawi Growth Development Strategies; 

- ii. United Nations Development Assistance Framework for Malawi (UNDAF); 

- iii. National Strategy for Sustainable Development 2004; 

- iv. National Environmental Policy (NEP) 2004;  

- v. National Forestry Policy of Malawi, 1996;  

- vi. National Land Resource Management Policy and Strategies (2000);  

- vii. Wildlife Policy (2000);  

- viii. Malawi Irrigation Policy and Development Strategy (2000);  

- ix. National Fisheries and Aquaculture Policy (2001);  

- x. National Land Policy (2002); 

- xi. National Environmental Action Plan 2002;  

- xii. National Climate Change Investment Plan (2013);  

- xiii. National HIV and AIDS Policy, 2003;  

- xiv. Malawi Energy Policy (2003);  

- xv. National Land Use Planning and Management Policy, 2005;  

- xvi. Food Security Policy (2006); 

- xvii. National Water Policy (2005);  

- xviii. Mines and Minerals Policy (2013); 

- xix. National Transport Policy (2015);  

- xx. National Construction Industry Policy (2015); 

- xxi. Water Resources Act (2013);  

- xxii. Mines and Minerals Act (1981);  

- xxiii. Disaster Preparedness and Relief Act (DPRA) (1991);  

- xxiv. Waterworks Act (1995);  

- xxv. Environment Management Act (1996);  

- xxvi. Forestry Act (1997);  

- xxvii. Fisheries Conservation and Management Act (1997); 

- xxviii. Road Traffic Act (1997);  

- xxix. Local Government Act (1998);  

- xxx. Energy Regulation Act (2004);  

- xxxi. National Parks and Wildlife Act (2004),  

- xxxii. Gender Equality Act (2013). 

**Table 1: National/sectoral policies, strategies and plans relevant for adaptation** 

|                  | **Title/Type**                                                            | **Year**  | **Objective**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|------------------|---------------------------------------------------------------------------|-----------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Climate**      | Malawi National <br>Climate Change <br>Policy                             | 2016      | The policy aims to effectively manage the impacts of climate change<br>through interventions that build and sustain the social and ecological<br>resilience of all Malawians; contribute towards the stabilization of<br>greenhouse gas concentrations in the atmosphere at a level that would<br>prevent dangerous human-induced interference with the climate system<br>within a timeframe that enables social, economic and environmental<br>development to proceed in a sustainable manner; Integrate climate<br>change into planning, development, coordination and monitoring of key<br>relevant sectors in a gender sensitive manner; and Integrate cross-cutting<br>issues into climate change management through an appropriate institutional <br>framework.                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                  | Second National <br>Communication                                         | 2011      | The objectives include; strengthening the technical and institutional <br>capacities of various public and private sector organizations to acquire<br>skills and competencies in mainstreaming climate change issues into their<br>respective sectoral programmes, policies and strategies, contributing to<br>global efforts in better understanding the various sources and sinks of<br>greenhouse gases, potential impacts of climate change and effective response<br>measures to achieve the ultimate goal of UNFCCC of stabilizing greenhouse gas<br>concentrations in the atmosphere to a level that would prevent dangerous <br>anthropogenic interference with the climate system, proposing climate change<br>projects aimed at finding solutions to climate change problems that<br>communities can adapt and/or use to mitigate climate change, enhancing general<br>awareness on climate change and climate change related issues, strengthening<br>dialogue, information exchange, networking and cooperation among various<br>stakeholders in the public and private sector organizations, including NGOs,<br>and the university, involved in climate change studies in accordance with Article <br>6 of the UNFCCC. |
|                  | NAPA                                                                      | 2006      | The NAPA seeks to increase the adaptive capacities of vulnerable communities to<br>adverse effects of climate change. Five urgent activities were rated high and<br>combined into project clusters. These include: Improving community resilience to<br>climate change through the development of sustainable rural livelihoods; restoring<br>forest in Upper, Middle and Lower Shire Valleys catchments to reduce siltation and<br>the associated water flow problems; improving agricultural production under erratic<br>rains and changing climatic conditions; improving Malawi’s preparedness to cope<br>with droughts and floods; and improving climate monitoring to enhance Malawi’s<br>early warning capability and decision making and sustainable utilization of Lake<br>Malawi and lakeshore areas resources.                                                                                                                                                                                                                                                                                                                                                                                                           |
|                  | National Climate<br>Change Investment<br>Plan                             | 2013-2018 | The primary objective is to increase climate change investments in Malawi.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|                  | National Environment <br>and Climate Change<br>Management                 | 2012-2016 | To inform, educate and communicate the public and ensure popular participation in the<br>management of environment, natural resources and climate change. This will be achieved<br>through the following specific objectives: increase public awareness, knowledge,<br>understanding and participation on environment and climate change among various target<br>groups, specifically rural communities and disadvantaged groups including women and<br>youth, promote popular participation in the implementation of the environment and<br>climate change ENRM and CC, enhance institutional and individual capacity for<br>communication in environment and climate change, foster collaboration, coordination<br>and networking of NECC communication interventions, enhance monitoring and evaluation<br>of NECC Strategy                                                                                                                                                                                                                                                                                                                                                                                                      |
| **Environment**  | National Forestry <br>Policy of Malawi                                    | 1996      | The objective of the policy is to improve the quality of life of the Malawi population,<br>particularly rural smallholders, and provide a stable local economy in order to reduce<br>the degenerative impact of development on the environment that often accompanies<br>poverty. The forest policy provides an enabling environment for making forests and tree<br>resources available to communities on a sustainable basis thereby promoting rural<br>development.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                  | National Environmental<br>Policy (NEP)                                    | 2004      | To minimize the adverse impact of climate change and variability to reduce air pollution<br>and greenhouse. However, the guiding principles and the strategies for achieving this<br>objective suggests that the policy orientation is focused on mitigation and not<br>adaptation.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|                  | National Environmental<br>Action Plan                                     | 2002      | To document and analyse all environmental issues and measures to alleviate them, to<br>promote sustainable use of natural resources in Malawi, to develop an environmental<br>protection and management plan                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                  | National Biodiversity<br>and Action Plan                                  |           | Outlines strategies for species monitoring and recovery, conservation of traditional<br>agro-biodiversity resources, conservation of aquatic and mountain biodiversity that<br>provides local communities with significant livelihood options for food security,<br>medicine and other uses.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| **Agriculture**  | Malawi Irrigation Policy<br>and Development Strategy                      | 2000      | Increase land under sustainable irrigation farming, Facilitate crop diversification<br>and intensification, Create an enabling environment for irrigated agriculture, <br>Optimize investment in irrigation development taking into account climate change,<br>Enhance capacity for irrigated agriculture, Promote a business culture in the<br>small-scale irrigated agriculture sector                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|                  | Food Security Policy                                                      | 2006      | Increasing agricultural productivity as well as diversity and sustainable<br>agricultural growth and development, Guarantee that all Malawians have at all times<br>physical and economic access to sufficient nutritious food required to lead a<br>healthy and active life                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                  | Draft National <br>Agricultural Policy                                    | Draft     | The draft policy seeks to promote adaptation and mitigation technologies and<br>interventions to minimize future adverse effects of climate change on agricultural<br>production and rural livelihoods. Some of the proposed ac2ons will support climate<br>change adaptation and mitigation in agriculture.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| **Energy**       | Malawi Energy Policy                                                      | 2013      | To improve the security and reliability of energy supply; Increase access to<br>affordable and modern technologies; Stimulate economic development and rural<br>transformation for poverty reduction; Improve the energy sector and governance; and<br>Mitigate environmental, safety and health impacts of energy production and utilization.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| **Health**       | National HIV and<br>AIDS Policy                                           | 2003      | To improve the provision and delivery of prevention, treatment, care and support<br>services for PLWAs, to reduce individual and societal vulnerability to HIV/AIDS by<br>creating an enabling environment, to strengthen the multi-sectoral and <br>multi-disciplinary institutional framework for coordination and implementation of<br>HIV/AIDS programs in the country                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| **Economic**     | Wildlife Policy                                                           | 2000      | The goal of this policy is to ensure proper conservation and management of wildlife<br>resources. The policy also increases sustainable utilization and equitable access to<br>the resources and fair sharing of the benefits from the resources for both present and<br>future generations of Malawi.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|                  | United Nations Development<br>Assistance Framework for<br>Malawi (UNDAF); | 2019-2023 | It incorporates the goals and principles that underpin Agenda 2030 and the 17 SDGs that<br>lie at its heart. It further guides the UN Agency programs ensuring UN wide coherence <br>and represents a strong collaborative link with the Government of Malawi’s development<br>aimsexpressed in Malawi Growth and Development Strategy MGDS III                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|                  | The Malawi Growth<br>Development Strategy III                             | 2017-2022 | Improved weather and climate monitoring for early warning, preparedness and timely<br>response. The strategy will promote effective and efficient generation, analysis and<br>utilization of reliable, responsive, high quality, up to date and timely climate services<br>; and Improving spatial (by area and agro-ecological zone) weather and climate monitoring<br>and prediction systems through automation and other IT advances.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|                  | National Strategy for<br>Sustainable Development<br>                      | 2004      | Seeks to reduce damage to property and loss of life caused by weather and climate natural<br>disasters and contributes to sustainable industrial production or meets the UNFCCC<br>obligations                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                  | Mines and Minerals Policy                                                 | 2013      | To attract investment in the mining sector, to formalize and improve small scale mining, <br>to create employment opportunities and economic diversification, to incorporate social<br>dimensions and empower women in mining, to promote measures to protect the environment,<br>as well as increase foreign exchange earnings.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| **Land**         | National Land Resource<br>Management Policy and<br>Strategies             | 2000      | The policy seeks to: improve and sustain the productivity of land for agricultural and<br>other uses through use of sound technologies to conserve soil and water resources, soil<br>fertility improvements and respecting livestock stocking capacities of land; Promote<br>rehabilitation of degraded lands for both agriculture and other uses with the aim of<br>sustaining the usability of these lands; and Control the dangers of surface run-off <br>water such as soil erosion and all its associated causative factors.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|                  | National Land Policy                                                      | 2002      | The goal of the policy is to ensure tenure security and equitable access to land by all<br>citizens of Malawi in order to facilitate ecologically balanced use of land resources.<br>The policy deals with issues of access to land, tenure security and sustainable<br>environmental management. The key focus of the policy is on issues of land ownership,<br>land use, land registration, national physical development plans, and establishing legal<br>framework for land use.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|                  | National Land Use<br>Planning and Management<br>Policy                    | 2005      | To secure social and economic development through optimum and ecologically balanced use<br>of land and land based resources                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| **Water**        | National Water Policy                                                     | 2005      | The objectives of the policy are to: Promote sustainable and integrated water resource<br>management and development to make water readily available and equitably accessible by<br>all Malawians; Ensure water of acceptable quality for all needs; Provide water supply<br>and sanitation services to all at affordable cost; Promote efficient and effective<br>utilization, conservation and protection of water resources for sustainable agriculture<br>and irrigation, fisheries, navigation, eco-tourism, forestry, hydropower and disaster<br>management and environmental protection.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| **Education**    | Malawi Strategy on<br>Climate Change Learning                             | 2013      | The objective of the Strategy is to strengthen human resources and skills development<br>for the advancement of green, low emission and climate resilient development                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| **Socio/Cultural** | Gender Equality Act                                                       | 2013      | The act seeks to promote gender equality, equal integration, and influence, and<br>empowerment, dignity in all functions of society, to prohibit and provide redress for<br>sex discrimination, harmful practices and sexual harassment, to provide public<br>awareness on promotion of gender equality.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|                  | National Gender Policy                                                    | 2000      | To strengthen gender mainstreaming and women empowerment at all levels in order to<br>facilitate attainment of gender equality and equity in Malawi, to reduce gender<br>inequalities and enhance participation of women, men, girls and boys in socio-economic<br>development processes.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| **Fisheries**    | National Fisheries and<br>Aquaculture Policy                              | 2001      | The policy provides clear guidelines for the development of the fisheries sector. The<br>policy also stipulates roles and responsibilities of public and private sector and civil<br>society organisations in the development of the fisheries industry                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|                  | Fisheries Conservation<br>and Management Act                              | 1997      | The act provides for the regulation, conservation and management of the fisheries of<br>Malawi.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | 

**Table 2:  General environmental laws and their policy relevance for adaptation**

| **Title/Type**                                              | **Year** | **Objective**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|-------------------------------------------------------------|----------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Environment<br>Management Act**                           | 2017     | This Act concerns the conservation and management of the environment in Malawi<br>and prescribes environmental standards. It also concerns the conservation and<br>management of biological (genetic) resources. The Act consists of 119 sections<br>divided into 17 Parts, covering main areas of environmental concern, some of<br>the areas covered are: The Environment Protection Authority; Environmental<br>Planning; Environmental and social impact assessment, audits and monitoring;<br>Environmental standards; Management of the Environment and Natural Resources;<br>Pollution Control; The Environment Fund. Climate Change is addressed in part<br>VIII concerning management of the environment and natural resources.                                                                           |
| **Energy Regulation<br>Act**                                | 2004     | This Act establishes the Energy Regulatory Authority to regulate the energy<br>sector, defines its functions and powers, and provide for licensing of energy<br>undertakings. Members of the Authority should have adequate knowledge related<br>renewable energy. The Authority shall notably promote energy efficiency and the<br>exploitation of renewable resources. The Authority is charged in art. 9.2.(i) to<br>promote the exploitation of renewable energy resources, and (e) to promote energy<br>efficiency and energy savings.                                                                                                                                                                                                                                                                        |
| **Rural Electrification<br>Act**                            | 2004     | This act makes provision for the promotion, funding, management and regulation of<br>rural electrification. Specific, more favourable rules are laid out for renewable<br>energy resources, including in terms of finance.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| **Disaster Preparedness<br>and Relief Act<br>(Cap. 33:05)** | 1992     | This Act makes provision for the prevention of disasters in Malawi and for disaster<br>preparedness and disaster mitigation. There shall be a Commissioner for Disaster<br>Preparedness and Relief who shall, among other things: supervise the establishment<br>of civil protection organizations and civil protection areas and control and direct<br>personnel, materials and services for the purposes of this Act. The Act provides<br>for the establishment of the National Disaster Preparedness and Relief Committee<br>of Malawi.                                                                                                                                                                                                                                                                         |
| **Wildlife Policy**                                         | 2000     | The policy embraces the following objectives: Ensure adequate protection of<br>representative ecosystems and their biological diversity by promoting and adopting<br>appropriate land management practices that are in line with sustainable utilization<br>considerations; Create public awareness and understanding on the need for wildlife<br>conservation and management and also their relationship to other land use issues;<br>Create a conducive environment for wildlife-based enterprises; Facilitate development<br>of necessary legislation and enforcement mechanisms in order to eliminate illegal<br>wildlife use; and Develop a cost effective legal, administrative and institutional<br>framework for managing wildlife resources without compromising the resources’<br>ecological attributes. |

### Institutional arrangements for climate change adaptation 
Malawi has several existing institutional structures to support climate change mitigation and adaptation policies (Malawi & Environmental Affairs Department, 
2016). The Malawi Constitution explicitly calls for environmental support, and the Malawi government has addressed climate change at the national, ministerial 
and departmental level (Amadu et al., 2020). Coordination between government agencies is a significant challenge for implementing the climate change policy 
components since climate change is a cross-cutting issue affecting most sectors, such as agriculture, human health, energy, fisheries, wildlife, water, forestry 
and gender (Hughes et al., 2019). Table 3 presents the evolution of the climate change agenda.

Table 3. Evolution of the national climate change agenda in Malawi: policies, programmes, institutions and linkage to political leadership [source] 

insert table 3 ...

