# National Adaptation Priorities

## Key risks and adaptation options
The key risks and adaptation options are presented based on analysis and summary of past and current data and reports up to 2020. The risk levels are divided into three temporal periods: near future (2020-2040 which is the period for which most of the granular [sub-regional] climate projections are based; mid-future (MF – covering the period 2040-2069) and far future (FF – the period 2070 to 2099). Risk level is assigned based on the criteria outlined below and expert judgment as presented in the reports in the framework outlined in the NAP technical guidelines report. It is evident that there are inadequately projected risks,particularly beyond 2040 for most of the systems/sectors and how to address this gap is addressed in section 8 of this report. 

**Risk assessment criteria (scores are provided in brackets, with a possible highest score of 24, and ranked as follows: high (20 or more; medium (15-19), low (14 and below):**
_The probability of a given climate hazard_ – The general probability for change in a climate hazard (such as temperature or extreme precipitation events) occurring.  

- **High** probability of the climate hazard occurring (3); 

- **Medium** probability of the climate hazard occurring (2); 

- **Low** probability of the climate hazard occurring (1). 

_The likelihood of impact occurrence_ – The likelihood that a change in a given climate hazard (e.g. temperature rise) will result in a particular impact (e.g. material failure). Examples of likelihood categories include: 

- **Virtually certain/already occurring** – Nearly certain likelihood of the impact occurring over the life of the infrastructure, and/or the climate hazard may already be impacting infrastructure (3); 

- **High** likelihood of the impact occurring over the life of the infrastructure (2); 

- **Moderate** likelihood of the impact occurring over the life of the infrastructure (1); 

- **Low** likelihood of the impact occurring over the life of the infrastructure (0). 

_The magnitude of the consequence_ – The combined impacts, should a given hazard occur, taking into account such factors as: 

- **Internal operations**, including the scope and duration of service interruptions, reputational risk, and the potential to encounter regulatory problems (1 - low to 3 – high); 

- **Capital and operating costs**, including all capital and operating costs to the stakeholder and revenue implications caused by the climate change impact; (1 - low to 3 – high); 

- **Number of people impacted**, including considerations related to any impacts on vulnerable populations (including, but not limited to seniors, low-income communities, mentally or physically disabled citizens, homebound residents, and children); (1 - low to 3 – high); 

- **Public health**, including worker safety; (1 - low to 3 – high); 

- **Economy**, including any impacts to the city’s economy, the price of services to customers, and clean-up costs incurred by the public; (1 - low to 3 – high); 

- **Environment**, including the release of toxic materials and impacts on biodiversity, the state’s ecosystems, and historic sites. (1 - low to 3 – high).

**Table XX: Projected climate changes and impacts. NF – near future (2020-2040), MF – mid-future (2041-2069), FF – far future (2070-2099)**

|                                                                                      **Parameter**                                                                                      |             **Hazard/Threat**             | **Impacts**                                                                                                                                                                                                                                   | **Vulnerabilities at Scale**                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |                                              **Affected Systems**                                               | **Risk <br>(NF)**  | **Risk <br>(MF)**  | **Risk <br>(FF)**  |
|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|:-----------------------------------------:|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:---------------------------------------------------------------------------------------------------------------:|:------------------:|:------------------:|:------------------:|
| Below normal rainfall <br> <br>(Actionaid, 2002; Aragie et al., 2018, 2018; <br>Future Climate for Africa, 2019; GCF, 2017; <br>Hughes et al., 2019; IFPRI, 2020; Mwanaleza, <br>2017)  | Drought                                   | Decreased crop production <br>Increased food crisis  <br>Depleted food reserves and unaffordable food prices  <br>Maize export ban  <br>By the 2090s, annual rainfall is projected to decrease throughout Malawi by -14%  <br>Water scarcity  | Several hundred hunger-related deaths <br>Erosion of social capital and informal social support systems in poor communities  <br>Malawi loses 4.6 % of its maize production each year due to droughts  <br>Droughts cause poverty to increase further <br>Lack of access to water in rural areas <br>Donor reliance                                                                                                                                                                                        | Crop production <br>Livestock production <br>Agriculture markets and trade <br>Social-Cultural <br>Health <br>  | High               | High               | Low                |
|  <br>(Actionaid, 2002; Aragie et al., 2018; <br>Future Climate for Africa, 2019; GCF, 2017; <br>Hughes et al., 2019; IFPRI, 2020)                                                       | Biodiversity loss                         | Declining lake levels Terrestrial and aquatic biodiversity decline <br>Decreasing fish catches <br> <br>Water pollution <br>Increased loss of vegetation                                                                                      | Substantial lake levels decline below the Lake Malawi Outflow Threshold <br>Decreased irrigation water supply in the Shire River Basin <br>Decreasing fish catches <br>Increasing human pressure and poor governance of natural resources <br>Increasing biological and chemical pollution of water from urban areas and industrial waste <br>Food insecurity in rural areas <br> Eutrophication of lakes leading to reduced biodiversity <br> <br>Loss of biodiversity and degeneration of the ecosystem  | Energy - hydropower <br>Fisheries <br>Ecosystems <br>Forestry <br>Water resources                               | Medium             | High               | High               |
| (Hughes et al., 2019; Japan International <br>Cooperation Agency (JICA), 2020; Mapulanga <br>& Naito, 2019)                                                                             | Land degradation                          | Declining soil fertility and soil loss <br>Water depletion <br>Solid water disposal <br>Deforestation <br>Erosion and sedimentation along slopes, river and stream banks                                                                      | Pollution and increased vulnerability to climate change  <br>Destruction of crop land <br>Sedimentation of water sources <br>Threat to social and economic development <br>Weak land tenure security <br>Poor environment health <br>Decreased access to piped water leading to the use of unprotected sources <br>Control erosion mitigation and reduce sedimentation <br>Protect source water from sedimentation                                                                                         | Ecosystems <br>Water resources <br>Health <br>                                                                  | High               | Med                | low                |
| Above normal rainfall <br> <br>(Actionaid, 2002; Hughes et al., 2019; IFPRI, <br>2020; Malawi, 2018; Ministry of Natural <br>Resources Energy and Mining, 2018)                         | Floods, storms, Intense runoff, <br>Hail  | Localized floods <br>Shire River flooding <br>Chronic and acute respiratory diseases <br>Generally wetter days for Malawi <br> <br>Disruption to infrastructure <br> <br>Increased landslides                                                 | A shortage of agricultural commodities  <br>Reduced maize production – about 12 % per year  <br>Maize production losses in the southern Malawi Average loss of 0.7 % of the annual GDP due <br>to the flooding of lakes and the overflowing of rivers. <br> Increased risk of contracting pneumonia in children <br>Increased risk of flooding from groundwater and surface water <br>Disruption of rail and road transportation                                                                           | Crop production <br>Livestock production <br>Health <br>Energy  <br>Water supplies <br>Transport                | High               | Med.               | low                |
| High rainfall variability  <br> <br>(GCF, 2017; Mtilatila et al., 2020; Pauw et <br>al., 2011) <br>                                                                                     |                                           | Changes in surface water flows including flooding <br>Lake fluctuations – below normal rainfall <br>                                                                                                                                          | The combined effects of temperature increase and rainfall decrease result in significantly lower flows in the Shire River <br>Reduced hydropower production  <br> <br>Increased poverty among urban and nonfarm households <br> <br>Increased national food shortages and higher domestic prices. <br>                                                                                                                                                                                                     | Energy <br>Water supplies <br>Social-Cultural <br>Food                                                          | High               | Med                | Med                |
| Shorter rainfall seasons, <br>Late onset of rainy season  <br> <br>(Hughes et al., 2019; Mwanaleza, 2017)                                                                               |                                           | Water shortages                                                                                                                                                                                                                               | Increased irrigation in rural areas <br>Increased poverty among the vulnerable rural communities                                                                                                                                                                                                                                                                                                                                                                                                           | Food production <br>Water supplies                                                                              | High               | Medium             | Low                |
| High temperatures  <br> <br>(Global Facility for Disaster Reduction and <br>Recovery (GFDRR), 2015; Hughes et al., <br>2019; Mtilatila et al., 2020)                                    | Heat <br>                                 | Water availability <br>Vermin and pests <br>Reduction in cloud cover <br>Increased irrigation <br>Increased mean annual temperature by 0.21°C per decade over the last 30 years                                                               | Decreasing water access trends during dry spells <br>Uncertain water availability <br>Increased risk of changes in distribution of vermin and pests <br>Skin conditions due to increased exposure to sunshine                                                                                                                                                                                                                                                                                              | Crop production <br>Livestock production <br>Water resources <br>Water supplies <br>Health                      | High               | Med                | Low                |
|                                                                                                                                                                                         | Biodiversity loss                         | Decreasing lake levels                                                                                                                                                                                                                        | An increase in temperature of 5 ◦C reduces the lake level by 1.42 m                                                                                                                                                                                                                                                                                                                                                                                                                                        | Fisheries <br>Energy production                                                                                 | Med                | Low                | Low                |

### Ranking adaptation actions
The adaptation options listed below have been ranked using a set of criteria that is partly modified from Sinay and Carter (2020) to make it simple for a large 
group of diverse stakeholders to come to consensus easily on the priority adaptation actions which will be unpacked in the project development plans. The 
adaptation options are clustered under over-arching adaptation themes which are the most likely to generate synergistic and wide-reaching co-benefits for the 
country as a whole. The project development plans will take into consideration other specific criteria that will assess aspects such as alignment with SDGs, 
Sendai Framework and Country GCF programmes, and inclusion of cross-cutting factors such as gender, vulnerable groups, policy and legislative reforms, and 
knowledge and capacity building at individual, community, institutional and systemic levels. 

**_Criteria_**:

| **Criteria**                           | **Indicator**     | **States/Score**  | **Values**  | **Observations**                                                                                                                         |
|----------------------------------------|-------------------|-------------------|-------------|------------------------------------------------------------------------------------------------------------------------------------------|
| **Uncertainty**                        | Scenario          | 1.5ᵒC             | 1           | The state of this indicator relates to the average temperature <br>increase used for planning. 1 – Near future                           |
|                                        |                   | 3ᵒC               | 2           |  2 – Mid future                                                                                                                          |
|                                        |                   | 5ᵒC               | 3           |  3 – Far future                                                                                                                          |
| **Costs**                              | Costs             | Low               | 3           | Low in comparison to other responses                                                                                                     |
|                                        |                   | Moderate          | 2           | Moderate in comparison to other responses                                                                                                |
|                                        |                   | High              | 1           | High in comparison to other responses                                                                                                    |
| **Decision-Making <br>time horizons**  | Timing            | Urgent            | 3           | If the implementation of the adaptation option can avoid life <br>threatening situations.                                                |
|                                        |                   | Convenient        | 2           | When the implementation of the adaptation option is not urgent, <br>but is in synchrony with ongoing development.                        |
|                                        |                   | Inconvenient      | 1           | Implementation of the adaptation option is not urgent and may <br>significantly impact the existing development plans                    |
| **Co-benefits**                        | Natural Systems   | Low               | 1           | No natural system co-benefits                                                                                                            |
|                                        |                   | Moderate          | 2           | Some benefits to natural systems                                                                                                         |
|                                        |                   | High              | 3           | Many benefits to natural systems                                                                                                         |
|                                        | Human Systems     | Low               | 1           | Few people benefit (social, economic/livelihoods, inclusivity, <br>gender)                                                               |
|                                        |                   | Moderate          | 2           | Moderate number of people benefit                                                                                                        |
|                                        |                   | High              | 3           | Large number of people benefit                                                                                                           |
| **Positive Systems Synergies**         | Positive impacts  | Low               | 1           | Largely confined within a single system                                                                                                  |
|                                        |                   | Moderate          | 2           | Links strongly to 2-3 systems                                                                                                            |
|                                        |                   | High              | 3           | Links strongly to 4 or more systems                                                                                                      |
| **Negative Systems Synergies**         | Negative impacts  | Low               | 3           | Low potential of negative impacts on another system (e.g. <br>aquaculture in dams can increase nutrient levels in water supply systems)  |
|                                        |                   | Moderate          | 2           | Medium potential of negative impacts on another system                                                                                   |
|                                        |                   | High              | 1           | High potential of negative impacts on another system                                                                                     |

**_Adaptation Options – Ranked:_**

1. Sustain and protect ecosystems and ecosystem goods and services including the integrity of water resources through: general tree planting and creation of 
buffer zones along river banks, lakes and wetlands in rural and urban areas; encouraging use of alternative energy sources and energy efficient appliances; 
capacity building and implementation of community based catchment and natural resources management; support agricultural intensification, and; enhanced law 
enforcement. 

2. Promote a climate-resilient food production system by implementing a range of strategies including: growing crops that are resilient to projected higher 
temperatures and early maturing to cope with the shifting growing season; use of organic manure to buttress high costs of fertilizers; provision of subsidies on 
farm inputs and access to loans; enhancing the infrastructure for and management of irrigation to reduce dependence on rain fed agriculture; strengthening and 
increasing the reach of extension services and training for farmers; access to drought and flood early warning information; provision of storage facilities for 
various crop and livestock products, and; creation of local markets through establishment of more agricultural companies. 

3. Forecasting and early warning systems for droughts and floods should be in place at sub-national scale and relevant for adoption and application in the 
different systems and increase funding to the national disaster risk management programs. 

4. Promotion of alternative economic opportunities for lakeshore people to alleviate fishing pressure and enhanced collaboration between the fishermen and the 
department of fisheries to promote sustainable fish utilization. 

5. In order to sustain energy production and distribution under climate change, the following measures should be undertaken: adopt alternative renewable energy 
sources like solar energy to diversify the energy mix and reduce environmental pressures from woodfuel demand; expand and reinforce water storage in dams by 
planting trees around dams; relocate settlement areas demarcated for dam construction, and; ensure that dams comply with all environmental regulations and laws. 

6. In order to ensure rural and urban water supplies under climate change, the following should be undertaken: restoration of the Lilongwe River catchment and 
dam catchments through re-afforestation; expansion of the Lunyangwa and Kamuzu dams; expansion of the water transmission and distribution networks; reduction 
of non-revenue water, and; exploration for new water sources such as the Likhubula project which extracts water from Mulanje mountain. 

7. Climate proof supply distribution systems (water/power), waste management systems (sanitation) and transport systems (roads, railways, bridges) and improve 
the connectivity within the different systems. 

8. Implement effective waste management in urban areas by: increasing the capacity of city or town assemblies to collect waste from residential areas; enhancing 
regular treatment of solid and liquid waste from industries and biomedical facilities before disposal and discharge; effecting automation and regular maintenance 
of the sewer systems to detect leakages and prevent blockages and obstruction; constructing landfills in areas less prone to floods, and; carrying out civic 
education of the public to change their attitudes such as towards waste segregation and recycling.  

9. Improve general population health through provision of sanitation and hygiene infrastructure and awareness creation, increasing the number of health workers, 
and relocation of people from flood prone areas. 
