# Implementation Strategy for the NAP

## Projects for implementation and guidelines 

Table XX: Existing country programmes for climate change adaptation 

 | Project / Programme                                                                                                                                                    | Objectives                                                                                                                                                                                                                                                                                                                                                                                            | Funders                                     | Implementing Agency                                          | Type of Project        | Duration                                                  | Priority Sectors                                                                    | Geographic Focus                                     |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------|--------------------------------------------------------------|------------------------|-----------------------------------------------------------|-------------------------------------------------------------------------------------|------------------------------------------------------|
| Building Climate Change Resilience in the Fisheries Sector in Malawi                                                                                                   | To improve Lake Malawi and coastal area community resilience to climate change through <br>the development of an early warning system, and sustainable fisheries and aquaculture, <br>in order to ensure food and livelihood security.                                                                                                                                                                | Least Developed Countries Fund              | FAO                                                          | Full Size              | 09/11/2016 to 31/07/2021                                  | Climate Change Adaptation                                                           | Malawi                                               |
| Shire Valley Transformation Program - I                                                                                                                                | To provide access to reliable gravity fed irrigation and drainage services, secure <br>land tenure for smallholder farmers, and strengthen management of wetlands and <br>protected areas in the Shire Valley.                                                                                                                                                                                        | GEF Trust Fund                              | The World Bank                                               | Full-size Project      | Project Approved for Implementation 08- Aug 2017          | Climate Change, Biodiversity                                                        | Malawi                                               |
| Technology Needs Assessments - Phase III (TNA Phase III)                                                                                                               | Provide participating countries targeted financial and technical support to prepare <br>new or updated and improved TNAs, including Technology Action Plans (TAPs), for <br>prioritized technologies that reduce greenhouse gas emissions, support adaptation to <br>climate change, and are consistent with Nationally Determined Contributions and national <br>sustainable development objectives  | GEF Trust Fund                              | United Nations Environment Programme                         | Full-size Project      | Project approved for implementation, 13/03/2018           | climate change                                                                      | Global                                               |
| Food-IAP: Enhancing the Resilience of Agro-Ecological Systems (ERASP)                                                                                                  | Enhance the Provision of Ecosystem services and improve the Productivity and Resilience<br>of Agricultural Systems of Vulnerable Rural Poor.                                                                                                                                                                                                                                                          | GEF Trust Fund                              | International Fund for Agricultural Development              | Full-size Project      | Project Approved for Implementation 02/04/2017            | Climate Change, Biodiversity, Land degradation                                      | Malawi                                               |
| Global Partnership on Wildlife Conservation and Crime Prevention for <br>Sustainable Development (PROGRAM)                                                             | Promote wildlife conservation, wildlife crime prevention and pro-conservation<br>sustainable development to reduce impacts to known threatened species from poaching and<br>illegal trade.                                                                                                                                                                                                            | GEF Trust Fund                              | The World Bank                                               | Full-size Project      | Concept proposed, 01 Jun 2015                             | Climate Change, Biodiversity, Land degradation                                      | Global                                               |
| Food-IAP: Fostering Sustainability and Resilience for Food Security in <br>Sub-Saharan Africa - An Integrated Approach (IAP-PROGRAM)                                   | Support countries in target geographies for integrating priorities to safeguard and <br>maintain ecosystem services into investments improving smallholder agriculture and food<br>value chains(Target 10-12 countries; 10 million ha of production landscapes; 2-3 million<br>beneficiary households)                                                                                                | GEF Trust Fund                              | International Fund for Agricultural Development              | Full-size Project      | Concept approved, 01 Jun 2015                             | Climate Change, Biodiversity, Land degradation                                      | Regional                                             |
| Climate Adaptation for Sustainable Water Supply                                                                                                                        | Sustain availability of water supply in the river courses &amp; climate proof water<br>resources outputs of the Sustainable Rural Water &amp; Sanitation Infrastructure for<br>Improved Health &amp; Livelihood project in five districts: Rumphi, Nkhotakota, Ntcheu,<br>Mangochi and Phalombe                                                                                                       | Least Developed Countries Fund              | African Development Bank                                     | Full-size Project      | Project Approved for Implementation,  10 Jan 2019         | Climate Change                                                                      | Malawi                                               |
| Umbrella Programme for Biennial Update Report to the United National<br>Framework Convention on Climate Change (UNFCCC)                                                | To support thirty nine (39) Least Developed Countries (LDCs) and Small Islands Developing<br>States (SIDS) prepare and submit good quality initial biennial update reports to the<br>UNFCCC that comply with the convention's reporting obligation                                                                                                                                                    | GEF Trust Fund                              | United Nations Environment Programme                         | Full-size Project      | Project Approved for Implementation, 23 Jun 2015          | Climate Change                                                                      | Global                                               |
| Building Climate Change Resilience in the Fisheries Sector in Malawi                                                                                                   | To improve the resilience of fishing communities around Lake Malombe to the effects of<br>climate change                                                                                                                                                                                                                                                                                              | Least Developed Countries Fund              | Food and Agriculture Organization                            | Full-size Project      | Project Approved for Implementation, 28 Aug 2016          | Climate Change                                                                      | Malawi                                               |
| Strengthening Climate Information and Early Warning Systems in Malawi to<br>Support Climate Resilient Development and Adaptation to Climate Change                     | To strengthen the weather, climate and hydrological monitoring capabilities, early<br>warning systems and available information for responding to extreme weather and planning<br>adaptation to climate change in Malawi.                                                                                                                                                                             | Least Developed Countries Fund              | United Nations Development Programme                         | Full-size Project      | Project closed, 02 Jul 2019                               | Climate Change                                                                      | Malawi                                               |
| Shire Natural Ecosystems Management Project                                                                                                                            | Shire River Basin planning framework developed to improve land and water management for<br>ecosystem and livelihood benefits in target areas                                                                                                                                                                                                                                                          | GEF Trust Fund                              | The World Bank                                               | Full-size Project      | Project closed, 31 May 2019                               | Climate Change, Land degradation, Biodiversity                                      | Malawi                                               |
| Malawi Climate Transparency Framework                                                                                                                                  | To strengthen the capacity of institutions in Malawi and set up an information system to<br>fulfill the enhanced Transparency requirements of the Paris Agreement.                                                                                                                                                                                                                                    | GEF Trust Fund                              | United Nations Environment Programme                         | Medium-size Project    | Proposed start and completion dates  1/1/2021-12/31/2023  | Climate Change                                                                      | Malawi                                               |
| Sustainable Forest Management Impact Program on Dryland Sustainable<br>Landscapes                                                                                      | To avoid, reduce, and reverse further degradation, desertication, and deforestation of<br>land and ecosystems in drylands through the sustainable management of production <br>landscapes                                                                                                                                                                                                             | GEF Trust Fund                              | Food and Agriculture Organization                            | Full-size Project      | Concept Approved, 01 Jun 2019                             | Climate Change, Biodiversity, Land Degradation                                      | Global                                               |
| Malawi-climate resilient and sustainable capture fisheries, aquaculture<br>development and watershed management project                                                | Aimed at improving the resilience of Malawi's inland fisheries and the associate land<br>management in the face of climate change, with a focus on local community engagement,<br>aims to complement and leverage an approved AfDB project focusing more on the enterprise<br>development aspects of the same challenge.                                                                              | Least Developed Countries Fund              | African Development Bank                                     | Full-size Project      | Concept Approved , 01 Dec 2019                            | Climate Change                                                                      | Malawi                                               |
| GEF-7 Africa Minigrids Program                                                                                                                                         | The Africa Minigrid Program seeks to support selected African countries to increase<br>energy access by reducing the cost and increasing commercial viability of renewable<br>energy mini-grids.                                                                                                                                                                                                      | GEF Trust Fund                              | United Nations Development Programme                         | Full-size Project      | Concept Approved, 01 Dec 2019                             | Climate Change                                                                      | Regional                                             |
| Adapting to Climate Change Through Integrated Risk Management Strategies<br>and Enhanced Market Opportunities for Resilient Food Security and<br>Livelihoods           | The project seeks to enhance climate adaptation and food security of households through<br>access to integrated climate risk management strategies and structured market<br>opportunities, with a focus on the most vulnerable                                                                                                                                                                        | Adaptation Fund                             | World Food Programme (WFP)                                   |                        | Start date -06/11/2020                                    | Food security                                                                       | Malawi / Africa                                      |
| South-South Cooperation Grant (SSC)                                                                                                                                    | On 16 February 2016, the Government of Malawi received peer support for accreditation<br>of a National Implementing Entity to the Adaptation Fund from the National Environment<br>Management Authority (NEMA) of Kenya.                                                                                                                                                                              | Adaptation Fund                             |  National Environmental Management Authority (NEMA), Kenya   | Readiness Grants       | Approval Date-16/02/2016                                  | Climate Change                                                                      | Malawi                                               |
| Enhancing Adaptive Capacity and Livelihood Diversification for the Rural<br>Poor of Northern Malawi                                                                    | The Project seeks to enhance resilience and adaptive capacity of rural communities that<br>are peripheral to Nkhata Bay, Mzimba, Karonga, Rumphi and Chitipa urban areas in the<br>northern Malawi.                                                                                                                                                                                                   | Adaptation Fund                             | African Development Bank (AfDB)                              | Regular sized project  | Proposal Submission date - 15 Feb 2019                    | Rural development                                                                   | Malawi                                               |
| Building urban climate resilience in South-eastern Africa                                                                                                              | To develop capacities and establish conditions to adapt to the adverse effects of climate<br>change in vulnerable cities of Madagascar, Malawi, Mozambique and the Union of Comoros;                                                                                                                                                                                                                  | Adaptation Fund                             | United Nations Human Settlements Programme (UN-Habitat)      |                        | Projected duration July 2018- January 2023                | Disaster risk reduction and early warning systems                                   | Madagascar, Malawi, Mozambique and Union of Comoros  |
| National Climate Change Programme                                                                                                                                      | This project enables the Government of Malawi to climate-proof the policies, strategies<br>and plans of the sectors of the economy most directly affected by climate change.                                                                                                                                                                                                                          | Green Climate Fund and patners              | Department of Environment Affairs, Malawi                    |                        | End date December 2020                                    | Climate Change                                                                      | Malawi                                               |
| Saving Lives and Protecting Agriculture Based Livelihoods in Malawi:<br>Scaling Up the Use of Modernized Climate Information and Early Warning<br>Systems” (M-Climes)  | The project will support the Government of Malawi to take important steps to save lives<br>and enhance livelihoods at risk from climate-related disasters.                                                                                                                                                                                                                                            | Green Climate Fund                          | Local and National Governments                               | Medium-size Project    | Projected start date: 01/05/2017                          | Climate Change                                                                      | Malawi                                               |
| Improving Preparedness to Agro-Climatic Extremes in Malawi (IPACE-Malawi)                                                                                              | To identify critical agro-climatic drought and flood indicators in three districts of<br>central and southern Malawi;  test the skill of short term to seasonal forecast tools in<br>simulating these indicators; and co-design agricultural climate services based on these<br>indicators/forecast tools.                                                                                            | Natural Environment Research Council, NERC  | University of Leeds, School of Earth and Environment         |                        | Oct 18 - Apr 21                                           | Agri-environmental science, <br>Climate & Climate Change, <br>Development studies   | Malawi                                               |
| Building Food Security and Social Resilience to HIV/AIDS in Malawi                                                                                                     | Working with farmers and stakeholders, researchers will document how climate change is<br>perceived or experienced by age, gender, HIV/AIDS status, food security status and<br>household structure. They will examine how government organizations are conceptualizing<br>and responding to climate change.                                                                                          | International Development Research Centre   | Several Researchers from different institutions              |                        | 22-03-2013 to  22-03-2017                                 | Food, Environment, Health                                                           | Malawi                                               |
|  Climate Adaptation for Rural Livelihoods and Agriculture (CARLA)                                                                                                      | The overall goal to improve communities’ resilience to climate variability and climate<br>change by developing and implementing adaptation strategies and measures that will<br>improve agricultural production and rural livelihoods were largely achieved.                                                                                                                                          | Global Environment Facility (GEF)           | African Development Bank                                     |                        | April 12, 2012-June 30, 2016                              | Climate Change                                                                      | Malawi                                               |
|  Global Climate Change Alliance (GCCA) – Malawi, Planning for climate<br>change                                                                                        | The project seeks to build capacity in climate change planning, with emphasis on<br>Malawi's irrigation sector.                                                                                                                                                                                                                                                                                       | European Union                              | Human Dynamics                                               |                        | Jun 2015-Dec 2017                                         | Environment                                                                         | Malawi                                               |
| Adaptation planning support for Malawi through UNEP                                                                                                                    | to reduce vulnerability of people in Malawi and to promote community and ecosystem<br>resilience to the impacts of climate change and gender-equitable adaptive capacity for<br>planning and implementing adaptation interventions.                                                                                                                                                                   | Green Climate Fund                          | United Nations Environment Programme                         | Concept note           | Proposal received by the GCF Secretareat, 26 Feb 2019     | Climate Change                                                                      | Malawi                                               |
| Building climate resilience of food insecure smallholder farmers in<br>Southern Malawi                                                                                 | The project addresses the adaptation needs of vulnerable smallholder farmers and their<br>communities in the Southern Region of Malawi, who have limited resilience and adaptive<br>capacities towards climate-related shocks.                                                                                                                                                                        | Green Climate Fund                          | Sahara and Sahel Observatory                                 | Concept note           | Date of Submission 11/18/2019                             | Climate Change, Food Security                                                       | Malawi                                               |
| Climate Investor One                                                                                                                                                   | Providing financing to develop renewable energy projects in regions with power deficits<br>to reduce energy costs and CO2 emissions.                                                                                                                                                                                                                                                                  | Green Climate Fund                          | Environmental Affairs Department                             | Large size project     | 20 Oct 2018- 21 June 2039                                 |                                                                                     | Malawi and 17 other countries                        |

### Promoting action by all actors and stakeholders: policy and capacity-development, outreach 
The National Adaptation Programme and Action (NAPA) (2016) outlines key stakeholders and actors described below: 

- **The Environmental Affairs Department (EAD)** is the designated government agency responsible for managing Malawi's environmental policies and programs. The EAD is accountable for coordinating NAPA projects, with line ministries carrying out specific projects. The EAD is also the lead organization in climate change planning for the Government of Malawi. 

- **Cabinet Committee on Health and Environment** is the highest level executive decision-making entity for environmental affairs in Malawi. The National Council 
for the Environment is a government watchdog that ensures coordination with various stakeholders, promotes compliance with environmental regulation, and 
monitors development projects to incorporate environmental concerns. 

- **Department of Climate Change and Meteorological Services** is tasked with providing climate and weather information and services. Its role in adaptation includes producing climate change scenarios and improving forecasting and early warning systems.  

- **Department of Poverty and Disaster Management Affairs** is the government watchdog for coordinating disaster and management activities. The department 
improves preparedness and response to changing disaster risks. The department also collaborates with relevant stakeholders in promoting the use of climate-proof 
structures, particularly in flood-prone areas 

- **Ministry of Agriculture and Food Security** promotes agricultural and rural development in Malawi. The ministry helps to educate and promote climate change 
adaptation practices as well as ensuring food security. 

- **Ministry of Irrigation and Water Development** ensures the provision and equitable access to water throughout Malawi. It enhances climate change adaptation 
through the provision of water supply as climate-induced threats increase. 

- **Ministry of Environment and Climate Change Management** plays a regulatory role by ensuring climate change projects and programmes are implemented following 
the international climate change protocols and conventions, national policies, regulations and guidelines. It also provides the infrastructure to ensure the 
information on climate change mechanisms has the widest reach. 

- **Environmental Affairs Department of the Ministry of Natural Resources and Environment** serves as the focal point for the United Nations Framework Convention on Climate Change (UNFCCC). It coordinates climate change adaptation planning for the government of Malawi.   

- **Malawi Red Cross Society** is a non-governmental organization that helps to reduce human suffering during disasters. The organization strives to reduce the 
vulnerability of those at risk and increase preparedness for more frequent disasters. 

- **National Smallholder Farmers' Association of Malawi** empowers and represent farmers interests. It promotes adaptation practices and supports access to risks 
pooling schemes. 

- **Academia and research institutions** who generate new local knowledge and develop appropriate adaptation solutions 

- **Private sector stakeholders** who provide and implement specific commercial adaptation solutions through public-private partnerships 

- **Media** to propagate climate change adaptation messages.

### Addressing vulnerabilities and risks in key systems and sectors 
The vulnerabilities and risks in key systems and sectors have been presented in sections 6 and 7 of this report. The approach to addressing these were discussed 
during the 2016 workshop and are outlined in table XX below. Some examples of potential projects and costs are listed in Table XXX below; these should be to the 
extent possible aligned with the GCF country programme and other relevant climate finance mechanisms (international and domestic) and implementing partners as 
well as take into account technology and capacity building. 

Table XX: Addressing vulnerability and risks in key sectors/systems (Map Stocktaking Report 2016)  

| ELEMENT A. LAY THE GROUNDWORK AND ADDRESS GAPS<br><br>1. Initiating and launching the NAP process<br><br><br>2. Stocktaking: Initiated in 2016 for identifying available<br>information on climate change impacts, vulnerability and adaptation,<br>and assessing gaps and needs of the enabling environment for the NAP process.<br><br>3. Addressing gaps and weaknesses in undertaking the NAP process<br><br>4. Comprehensively and iteratively assessing development needs and climate<br>vulnerabilities | - The NAP process was launched officially on September 2, 2014, where workshops were<br>conducted across the country for capacity building and raising awareness.<br><br>- Malawi is also an active participant in the Open NAP initiative being supported by the LDC Expert Group (LEG)<br><br><br>- The stocktaking recommended the following thematic areas be considered for the medium and long-term adaptation<br>planning horizon of the NAP process: 1. Improving access to energy sources, 2. Increasing resilience of food<br>production systems, 3. Improving weather and climate forecasting, 4. Improving agriculture to ensure farmers<br>are moving from subsistence to commercialization, 5. Promoting catchment management practices, 6. Integrated<br>water resource management to encourage large scale commercial irrigation, 7. Population change and human<br>settlements, 8. Civic education and adult literacy, 9. Infrastructure development, 10. Inclusiveness of gender,<br>disability and other socially excluded vulnerable groups in implementing climate change adaptation interventions,<br>11. Monitoring of climate: adequate database and easy access for all people, 12. Development of collaborative<br>wildlife management, 13. Education, science and green technology<br><br><br>- While the stocktaking did not find conspicuous gaps in the landscape of climate change knowledge relevant to<br>Malawi, it was clear that the most accurate and often-referenced modelling data is now somewhat obsolete. Thus<br>newer research will better warn the NAP process is going forward.<br><br>- Similarly, while there is an adequate amount of literature for each of the sectors to have an initial<br>understanding of future threats from climate change, there is a need for more Malawi-specific studies, along<br>with more sector-specific studies.<br><br><br>- The main weaknesses the stocktaking found in Malawi's climate change adaptation architecture were low levels<br>of awareness about climate change at all levels of society, a limited number of experts in the various sectors<br>of climate change adaptation; absence of climate change centres of learning and research; lack of locally driven<br>sustainable climate change funding; and weak institutional capacity for managing climate change.<br><br>- Climate vulnerabilities will be assessed at the sector, sub-national and national levels and involves analyzing<br>the current climate to identify vulnerability, risks, and trends in variables and indices at the national,<br>regional or ecosystem level that could be used to support planning and decision making. Comprehensively analyze<br>community resilience and the staff to be trained on methodologies for climate risk assessment and adaptation<br>planning, including the integration of climate change in budgeting processes |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
### Better informed decision-making: climate information services, early warning, science and technology, decision-support modeling, research 

Essential cross-cutting projects/programmes would include: 

- Improving community resilience through the development of sustainable rural livelihoods. 

- Restoring forests in the Upper, Middle, and Lower Shire valleys. 

- Improving agricultural production under erratic rains and changing climatic conditions. 

- Improving Malawi's preparedness to cope with droughts and floods. 

- Improving climate monitoring to enhance Malawi's early warning capability and decision-making. 

- Improving sustainable utilization of Lake Malawi and its lakeshore. 
