# Reporting

## Adaptation communications/NDCs 
All Parties are required to submit their NDCs every five years (e.g. 2020, 2025, 2030), regardless of their respective implementation time frames. The NAP process 
is being developed for the first time. It is preferred that these two types of reports are be staggered, rather than submitted during the same year, so that they in 
essence feed into each other in a progressive manner and lessons learned can be integrated into the evolving NAP process. 

## Links to SDG voluntary reporting and Sendai Framework Monitor 
It is reported in the UN SDG Knowledge Platform10 that Malawi has operationalized the SDG Agenda through its national development planning framework, the Malawi 
Growth and Development Strategy (MGDS III). It is recognised that the Malawi National Climate Change Management Policy: serves as an overarching reference document 
for policy makers in Government, the private sector, civil society, and donors concerning climate change as a priority development issue and feeds into the 
country’s Sector Wide Approaches (SWAPs) to inform strategic government programming, including programming for the achievement of the Sustainable Development Goals 
(SDGs). The Ministry of Natural Resources, Energy and Mining has the role of facilitating, coordinating and advising in ensuring the implementation of the NCCMP as 
well as setting and enforcement of relevant and acceptable standards. The Disaster Preparedness and Relief Act (DPRA) 1991 probably needs to be updated and brought 
into line with the latest principals and objectives on disaster risk reduction as laid out in the Sendai Framework. 

### Gender
In 2019, Malawi's female population accounts 50.67% of the 18.63 million total approximated population (REF).   Malawi ranks 173 out of 188 on the UN’s Gender 
Inequality Index (GII) (USAID 2016) with a Gender Development Index (GDI) of 0.374 indicative of sharp gender disparities between men and women (NAP Stocktaking 
report 2016). In Malawi, gender inequalities are apparent in all spheres. For instance, women have limited access and control to means of production such as 
land, credit and technology, and limited rights and control on their reproductive health. The challenge for reducing gender inequality is to mainstream gender 
issues in all aspects of development (Vision 2020). Women represent the main source of agricultural labor in Africa and the fact that agriculture in tropical and 
subtropical areas is one of the sectors most vulnerable to climate change, some women remain vulnerable and poor (Irish Aid, 2018). 

Cultural and legal norms poorly protect women making them be, typically less well educated, less numerate and literate than their male contemporaries. In Malawi, 
only 16.7 of parliamentary seats are held by women. There are less women who have reached secondary level of education (14.9%) in comparison to male counterparts 
(24.2%) 71. Due to gender and social exclusion, women often face barriers in accessing the opportunities arising from economic growth, or in taking advantage of 
new resources, leadership opportunities, and assets created through climate investments. Where women are heads of households due to men’s migration to towns, 
they make all decisions relating to land development. GoM has made gender mainstreaming a priority in its development agenda in order to narrow the inequality 
gap by ensuring rights of rural women are protected in regard to food security, non-discriminatory access to resources, and equitable participation in decision 
making processes (Masi 2017).  

Climate change is going to inhibit women’s development and gender empowerment efforts by creating more challenging economic circumstances for the population as a 
whole, but also by making access to natural resources (water, fuel-wood etc) more difficult. Women also have fewer material and financial resources at hand – and 
often less autonomy – to help themselves cope with shocks like natural disasters. Negative implications of climate change on all the sectors discussed above are 
likely to disproportionately affect women in both direct and indirect ways (NAP Stocktaking Report 2016). 

During NAPA consultation process, stakeholders recommended promotion of gender, disability and other socially excluded vulnerable groups in implementation of 
climate change adaptation interventions as one of the thematic areas. The Malawi Growth and Development Strategy III includes the following strategies to promote 
on gender mainstreaming: 

- Increasing equitably access, control and utilization of social and economic services by youth and women 

- Ensuring the consistent implementation of gender responsive budgeting across sectors 

- Ensuring the effective participation of children, youth and women in decision making processes 

- Increasing youth and women participation in the economy including development initiatives at all levels.  

These strategic priorities on gender should be reflected in adaptation programme design. 
